#!/bin/sh

echo "/* File generated by script. Do not edit. */"        >  version.h
echo "#define PSND_VERSION \"ProsPectND version 2.5 ("`date`")\"" >> version.h
echo ""                                                    >> version.h
