/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.core;
// Generated 3/08/2006 16:48:23 by Hibernate Tools 3.1.0.beta4



/**
* BiologicalContextToGlycoconjugate generated by hbm2java
*/

public class BiologicalContextToGlycoconjugate extends org.eurocarbdb.dataaccess.BasicEurocarbObject implements java.io.Serializable {


    // Fields    

     private int biologicalContextToGlycoconjugateId;
     private BiologicalContext biologicalContext;
     private Glycoconjugate glycoconjugate;


    // Constructors

    /** default constructor */
    public BiologicalContextToGlycoconjugate() {
    }

    
    /** full constructor */
    public BiologicalContextToGlycoconjugate(BiologicalContext biologicalContext, Glycoconjugate glycoconjugate) {
        this.biologicalContext = biologicalContext;
        this.glycoconjugate = glycoconjugate;
    }
    

   
    // Property accessors

    public int getBiologicalContextToGlycoconjugateId() {
        return this.biologicalContextToGlycoconjugateId;
    }
    
    public void setBiologicalContextToGlycoconjugateId(int biologicalContextToGlycoconjugateId) {
        this.biologicalContextToGlycoconjugateId = biologicalContextToGlycoconjugateId;
    }

    public BiologicalContext getBiologicalContext() {
        return this.biologicalContext;
    }
    
    public void setBiologicalContext(BiologicalContext biologicalContext) {
        this.biologicalContext = biologicalContext;
    }

    public Glycoconjugate getGlycoconjugate() {
        return this.glycoconjugate;
    }
    
    public void setGlycoconjugate(Glycoconjugate glycoconjugate) {
        this.glycoconjugate = glycoconjugate;
    }
   








}
