package org.eurocarbdb.dataaccess.core;
// Generated 17-Nov-2009 06:37:56 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import org.apache.log4j.Logger;
import org.eurocarbdb.dataaccess.Contributed;

/**
 * BiologicalContextContributor generated by hbm2java
 */
public class BiologicalContextContributor  implements java.io.Serializable, Contributed, Cloneable {

	 /** Logging handle. */
    static final Logger log = Logger.getLogger( BiologicalContext.class );
    
	private int biologicalContextContributorId;
	private Date dateEntered;
	private String comments;
	private Contributor contributor;
	private BiologicalContext biologicalContext;

    public BiologicalContextContributor() {
    }

	
    public BiologicalContextContributor(Contributor contributor, BiologicalContext biologicalContext) {
        this.contributor = contributor;
        this.biologicalContext = biologicalContext;
    }
    
    public BiologicalContextContributor(Date dateEntered, String comments, Contributor contributor, BiologicalContext biologicalContext) {
       this.dateEntered = dateEntered;
       this.comments = comments;
       this.contributor = contributor;
       this.biologicalContext = biologicalContext;
    }
   
    public int getBiologicalContextContributorId() {
        return this.biologicalContextContributorId;
    }
    
    public void setBiologicalContextContributorId(int biologicalContextContributorId) {
        this.biologicalContextContributorId = biologicalContextContributorId;
    }
    public Date getDateEntered() {
        return this.dateEntered;
    }
    
    public void setDateEntered(Date dateEntered) {
        this.dateEntered = dateEntered;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Contributor getContributor() {
        return this.contributor;
    }
    
    public void setContributor(Contributor contributor) {
        this.contributor = contributor;
    }
    public BiologicalContext getBiologicalContextId() {
        return this.biologicalContext;
    }
    
    public void setBiologicalContextId(BiologicalContext biologicalContextId) {
        this.biologicalContext = biologicalContextId;
    }

      /*  appendComment  *//*******************************************
    *
    *   Appends the given comment onto existing comments for this context.
    *   This method simply appends the given text directly to existing
    *   comments but future revisions of this method might add a 
    *   timestamp/user header to the comment upon appending.
    */
    public void appendComment( String comment ) 
    {
    	if(comment != null){
    		String text = comment.trim();
    		assert text != null;
    		assert text.length() > 0;
    		if ( log.isDebugEnabled() )
    			log.debug( "appending the following comment to biological context:\n" 
    					+ text 
    			);

    		setComments( getComments() + "\n\n" + text );
    	}
    }
    
    public BiologicalContext getBiologicalContext() {
        return this.biologicalContext;
    }

    public void setBiologicalContext(BiologicalContext biologicalContext) {
        this.biologicalContext = biologicalContext;
    }
}