/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.core;
// Generated 3/08/2006 16:48:25 by Hibernate Tools 3.1.0.beta4



/**
* Glycoprotein generated by hbm2java
*/

public class Glycoprotein extends org.eurocarbdb.dataaccess.BasicEurocarbObject implements java.io.Serializable {


    // Fields    

     private int glycoproteinId;
     private String glycoproteinName;
     private String accessionUniprot;


    // Constructors

    /** default constructor */
    public Glycoprotein() {
    }

    /** minimal constructor */
    public Glycoprotein(String glycoproteinName) {
        this.glycoproteinName = glycoproteinName;
    }
    
    /** full constructor */
    public Glycoprotein(String glycoproteinName, String accessionUniprot) {
        this.glycoproteinName = glycoproteinName;
        this.accessionUniprot = accessionUniprot;
    }
    

   
    // Property accessors

    public int getGlycoproteinId() {
        return this.glycoproteinId;
    }
    
    public void setGlycoproteinId(int glycoproteinId) {
        this.glycoproteinId = glycoproteinId;
    }

    public String getGlycoproteinName() {
        return this.glycoproteinName;
    }
    
    public void setGlycoproteinName(String glycoproteinName) {
        this.glycoproteinName = glycoproteinName;
    }

    public String getAccessionUniprot() {
        return this.accessionUniprot;
    }
    
    public void setAccessionUniprot(String accessionUniprot) {
        this.accessionUniprot = accessionUniprot;
    }
   








}
