/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.core;
// Generated 3/08/2006 16:48:23 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
* Glycoconjugate generated by hbm2java
*/

public class Glycoconjugate extends org.eurocarbdb.dataaccess.BasicEurocarbObject implements java.io.Serializable {


    // Fields    

     private int glycoconjugateId;
     private String glycoconjugateType;
     private String glycoconjugateTable;
     private int glycoconjugateTableId;
     private Set<BiologicalContextToGlycoconjugate> biologicalContextToGlycoconjugates = new HashSet<BiologicalContextToGlycoconjugate>(0);


    // Constructors

    /** default constructor */
    public Glycoconjugate() {
    }

    /** minimal constructor */
    public Glycoconjugate(String glycoconjugateType, String glycoconjugateTable, int glycoconjugateTableId) {
        this.glycoconjugateType = glycoconjugateType;
        this.glycoconjugateTable = glycoconjugateTable;
        this.glycoconjugateTableId = glycoconjugateTableId;
    }
    
    /** full constructor */
    public Glycoconjugate(String glycoconjugateType, String glycoconjugateTable, int glycoconjugateTableId, Set<BiologicalContextToGlycoconjugate> biologicalContextToGlycoconjugates) {
        this.glycoconjugateType = glycoconjugateType;
        this.glycoconjugateTable = glycoconjugateTable;
        this.glycoconjugateTableId = glycoconjugateTableId;
        this.biologicalContextToGlycoconjugates = biologicalContextToGlycoconjugates;
    }
    

   
    // Property accessors

    public int getGlycoconjugateId() {
        return this.glycoconjugateId;
    }
    
    public void setGlycoconjugateId(int glycoconjugateId) {
        this.glycoconjugateId = glycoconjugateId;
    }

    public String getGlycoconjugateType() {
        return this.glycoconjugateType;
    }
    
    public void setGlycoconjugateType(String glycoconjugateType) {
        this.glycoconjugateType = glycoconjugateType;
    }

    public String getGlycoconjugateTable() {
        return this.glycoconjugateTable;
    }
    
    public void setGlycoconjugateTable(String glycoconjugateTable) {
        this.glycoconjugateTable = glycoconjugateTable;
    }

    public int getGlycoconjugateTableId() {
        return this.glycoconjugateTableId;
    }
    
    public void setGlycoconjugateTableId(int glycoconjugateTableId) {
        this.glycoconjugateTableId = glycoconjugateTableId;
    }

    public Set<BiologicalContextToGlycoconjugate> getBiologicalContextToGlycoconjugates() {
        return this.biologicalContextToGlycoconjugates;
    }
    
    public void setBiologicalContextToGlycoconjugates(Set<BiologicalContextToGlycoconjugate> biologicalContextToGlycoconjugates) {
        this.biologicalContextToGlycoconjugates = biologicalContextToGlycoconjugates;
    }
   








}
