/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.core;
// Generated 3/08/2006 16:48:23 by Hibernate Tools 3.1.0.beta4



/**
* PerturbationRelations generated by hbm2java
*/

public class PerturbationRelations extends org.eurocarbdb.dataaccess.BasicEurocarbObject implements java.io.Serializable {


    // Fields    

     private int perturbationId;
     private Perturbation perturbation;
     private int leftIndex;
     private int rightIndex;


    // Constructors

    /** default constructor */
    public PerturbationRelations() {
    }

    
    /** full constructor */
    public PerturbationRelations(Perturbation perturbation, int leftIndex, int rightIndex) {
        this.perturbation = perturbation;
        this.leftIndex = leftIndex;
        this.rightIndex = rightIndex;
    }
    

   
    // Property accessors

    public int getPerturbationId() {
        return this.perturbationId;
    }
    
    public void setPerturbationId(int perturbationId) {
        this.perturbationId = perturbationId;
    }

    public Perturbation getPerturbation() {
        return this.perturbation;
    }
    
    public void setPerturbation(Perturbation perturbation) {
        this.perturbation = perturbation;
    }

    public int getLeftIndex() {
        return this.leftIndex;
    }
    
    public void setLeftIndex(int leftIndex) {
        this.leftIndex = leftIndex;
    }

    public int getRightIndex() {
        return this.rightIndex;
    }
    
    public void setRightIndex(int rightIndex) {
        this.rightIndex = rightIndex;
    }
   








}
