package org.eurocarbdb.dataaccess.core;
// Generated 10-Nov-2009 11:05:15 by Hibernate Tools 3.2.2.GA



/**
 * TaxonomyProteomeSkRanked generated by hbm2java
 */
public class TaxonomyProteomeSkRanked  implements java.io.Serializable {


     private int ncbiId;
     private String rank;
     private Taxonomy taxonomy;

    public TaxonomyProteomeSkRanked() {
    }

	
    public TaxonomyProteomeSkRanked(int ncbiId, String rank) {
        this.ncbiId = ncbiId;
        this.rank = rank;
    }
    public TaxonomyProteomeSkRanked(int ncbiId, String rank, Taxonomy taxonomy) {
       this.ncbiId = ncbiId;
       this.rank = rank;
       this.taxonomy = taxonomy;
    }
   
    public int getNcbiId() {
        return this.ncbiId;
    }
    
    public void setNcbiId(int ncbiId) {
        this.ncbiId = ncbiId;
    }
    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }
    
    public Taxonomy getTaxonomy() {
        return this.taxonomy;
    }
    
    public void setTaxonomy(Taxonomy taxonomy) {
        this.taxonomy = taxonomy;
    }




}


