/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.core;
// Generated 3/08/2006 16:48:24 by Hibernate Tools 3.1.0.beta4

import java.io.Serializable;

import org.eurocarbdb.dataaccess.BasicEurocarbObject;

/**
* TaxonomyRelations generated by hbm2java
*/

public class TaxonomyRelations extends BasicEurocarbObject implements Serializable 
{

    // Fields    

     private int taxonomyId;
     private Taxonomy taxonomy;
     private int leftIndex;
     private int rightIndex;
     private int relativeImportance;


    // Constructors

    /** default constructor */
    public TaxonomyRelations() 
    {
    }

    
    /** full constructor */
    public TaxonomyRelations(Taxonomy taxonomy, int leftIndex, int rightIndex) 
    {
        this.taxonomy = taxonomy;
        this.leftIndex = leftIndex;
        this.rightIndex = rightIndex;
    }
    

   
    // Property accessors

    public int getTaxonomyId() 
    {
        return this.taxonomyId;
    }
    
    public void setTaxonomyId(int taxonomyId) 
    {
        this.taxonomyId = taxonomyId;
    }

    public Taxonomy getTaxonomy() 
    {
        return this.taxonomy;
    }
    
    public void setTaxonomy(Taxonomy taxonomy) 
    {
        this.taxonomy = taxonomy;
    }

    public int getLeftIndex() 
    {
        return this.leftIndex;
    }
    
    public void setLeftIndex(int leftIndex) 
    {
        this.leftIndex = leftIndex;
    }

    public int getRightIndex() 
    {
        return this.rightIndex;
    }
    
    public void setRightIndex(int rightIndex) 
    {
        this.rightIndex = rightIndex;
    }
   
}
