/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.core;
// Generated 3/08/2006 16:48:25 by Hibernate Tools 3.1.0.beta4



/**
* TissueTaxonomyRelations generated by hbm2java
*/

public class TissueTaxonomyRelations extends org.eurocarbdb.dataaccess.BasicEurocarbObject implements java.io.Serializable {


    // Fields    

     private int tissueTaxonomyId;
     private TissueTaxonomy tissueTaxonomy;
     private int leftIndex;
     private int rightIndex;


    // Constructors

    /** default constructor */
    public TissueTaxonomyRelations() {
    }

    
    /** full constructor */
    public TissueTaxonomyRelations(TissueTaxonomy tissueTaxonomy, int leftIndex, int rightIndex) {
        this.tissueTaxonomy = tissueTaxonomy;
        this.leftIndex = leftIndex;
        this.rightIndex = rightIndex;
    }
    

   
    // Property accessors

    public int getTissueTaxonomyId() {
        return this.tissueTaxonomyId;
    }
    
    public void setTissueTaxonomyId(int tissueTaxonomyId) {
        this.tissueTaxonomyId = tissueTaxonomyId;
    }

    public TissueTaxonomy getTissueTaxonomy() {
        return this.tissueTaxonomy;
    }
    
    public void setTissueTaxonomy(TissueTaxonomy tissueTaxonomy) {
        this.tissueTaxonomy = tissueTaxonomy;
    }

    public int getLeftIndex() {
        return this.leftIndex;
    }
    
    public void setLeftIndex(int leftIndex) {
        this.leftIndex = leftIndex;
    }

    public int getRightIndex() {
        return this.rightIndex;
    }
    
    public void setRightIndex(int rightIndex) {
        this.rightIndex = rightIndex;
    }
   








}
