/* XPM */
static char * psnd_icon16_xpm[] = {
"16 16 12 1",
" 	c None",
".	c #000000",
"+	c #938E45",
"@	c #B2AA3E",
"#	c #D6CA22",
"$	c #EAEA15",
"%	c #F4210E",
"&	c #3E5B6D",
"*	c #3A5E75",
"=	c #347299",
"-	c #2C82B7",
";	c #2092D8",
"................",
"................",
"................",
".....++++++++...",
"....@@@@@@@@+...",
"...########@+...",
"..$$$$$$$$#@+...",
".%%%%%%%%$#@+...",
".%%%%%%%%$#&&&&.",
".%%%%%%%%$****..",
".%%%%%%%%====...",
".%%%%-------....",
".%%%;;;;;;;.....",
".%%%%%%%%$......",
".%%%%%%%%.......",
"................"};
/* XPM */
static char * psnd_icon32_xpm[] = {
"32 32 18 1",
" 	c None",
".	c #138437",
"+	c #76EF13",
"@	c #842813",
"#	c #9B8E4D",
"$	c #B29F42",
"%	c #C9B036",
"&	c #D8BA24",
"*	c #E2C118",
"=	c #EDC915",
"-	c #FF3502",
";	c #2C2C8E",
">	c #22228E",
",	c #2A2A99",
"'	c #2424AD",
")	c #2323C4",
"!	c #1F1FD3",
"~	c #1B1BE2",
"                                ",
"                                ",
"                                ",
"             .......            ",
"            .+++++..            ",
"           .+++++.+.            ",
"          .......++.            ",
"          .+++++.++.            ",
"         @.+++++.++.@@@@        ",
"        @#.+++++.+.###@@        ",
"       @$$.+++++..$$$@#@        ",
"      @%%%.+++++.%%%@$#@        ",
"     @&&&&&&&&&&&&&@%$#@        ",
"    @*************@&%$#@        ",
"   @=============@*&%$#@        ",
"  @@@@@@@@@@@@@@@=*&%$#@        ",
"  @-------------@=*&%$#@        ",
"  @-------------@=*&%$#@        ",
"  @-------------@=*&%$#@        ",
"  @-------------@=*&%$#@        ",
"  @-------------@=*&;;;;;;;;;   ",
"  @-------------@=*>>>>>>>>>    ",
"  @-------------@=,,,,,,,,,     ",
"  @-------------@'''''''''      ",
"  @-------)))))))))))))))       ",
"  @------!!!!!!!!!!!!!!!        ",
"  @-----~~~~~~~~~~~~~~~         ",
"  @-------------@=*@            ",
"  @-------------@=@             ",
"  @-------------@@              ",
"  @@@@@@@@@@@@@@@               ",
"                                "};
/* XPM */
static char * psnd_icon32_xpm__[] = {
"32 32 22 1",
" 	c None",
".	c #000000",
"+	c #5D6E89",
"@	c #D334CE",
"#	c #4E891E",
"$	c #5EAA20",
"%	c #76EF13",
"&	c #827847",
"*	c #9B8E4D",
"=	c #B29F42",
"-	c #C9B036",
";	c #D8BA24",
">	c #E2C118",
",	c #EDC915",
"'	c #FF3502",
")	c #2C2C8E",
"!	c #22228E",
"~	c #2A2A99",
"{	c #2424AD",
"]	c #2323C4",
"^	c #1F1FD3",
"/	c #1B1BE2",
"................................",
"................................",
".....++++++++++++++++...........",
".....++++++++++++++++...........",
".....++++++++++++++++@@@@@@@@@..",
".....++++++++#####+++@@@@@@@@@..",
".....+++++++$$$$$#+++@@@@@@@@@..",
".....++++++%%%%%$#+++@@@@@@@@@..",
".....+++++&%%%%%$#&&&&&&@@@@@@..",
".....++++**%%%%%$******&@@@@@@..",
".....+++===%%%%%======*&@@@@@@..",
".....++----%%%%%-----=*&@@@@@@..",
".....+;;;;;;;;;;;;;;-=*&@@@@@@..",
".....>>>>>>>>>>>>>>;-=*&@@@@@@..",
"....,,,,,,,,,,,,,,>;-=*&@@@@@@..",
"...'''''''''''''',>;-=*&@@@@@@..",
"...'''''''''''''',>;-=*&@@@@@@..",
"...'''''''''''''',>;-=*&@@@@@@..",
"...'''''''''''''',>;-=*&@@@@@@..",
"...'''''''''''''',>;-=*&@@@@@@..",
"...'''''''''''''',>;))))))))@@..",
"...'''''''''''''',>!!!!!!!!@@@..",
"...'''''''''''''',~~~~~~~~@@@@..",
"...''''''''''''''{{{{{{{{@@@@@..",
"...''''''']]]]]]]]]]]]]]........",
"...''''''^^^^^^^^^^^^^^.........",
"...'''''//////////////..........",
"...'''''''''''''',>.............",
"...'''''''''''''',..............",
"...''''''''''''''...............",
"................................",
"................................"};


/* XPM */
static char *divx_pix_xxx[] = {
/* width height num_colors chars_per_pixel */
"    32    15        2            1",
/* colors */
". c #000000000000",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaa.aaaaaaaaaaaaaaaaaaa.aaaaaa",
"aaaaa..aaaaaa.aaaaa.aaaaaa..aaaaa",
"aaaa...aaaaaaa.aaa.aaaaaaa...aaaa",
"aaa....aaaaaaaa.a.aaaaaaaa....aaa",
"aa........aaaaaa.aaaaaa........aa",
"aaa....aaaaaaaa.a.aaaaaaaa....aaa",
"aaaa...aaaaaaa.aaa.aaaaaaa...aaaa",
"aaaaa..aaaaaa.aaaaa.aaaaaa..aaaaa",
"aaaaaa.aaaaaaaaaaaaaaaaaaa.aaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
};
/* XPM */
static char * divx_pix[] = {
"32 15 9 1",
" 	c None",
".	c #804C48",
"+	c #000000",
"@	c #880000",
"#	c #000084",
"$	c #FFFFFF",
"%	c #501418",
"&	c #502420",
"*	c #181818",
"                                ",
"          .....   +@   +        ",
"    #    .     @   +@ +@   #    ",
"    #   .       @   ++@    #    ",
"   ##   @ $$    @   ++@    ##   ",
"   ##   @ $$    @  +@ +@   ##   ",
"  ###   @       @ +@   +   ###  ",
" ###### %       @        ###### ",
"  ###    %     @&          ###  ",
"   ##     %%%%@*&&         ##   ",
"   ##           *&&        ##   ",
"    #            *&&       #    ",
"    #             *        #    ",
"                                ",
"                                "};

static char *mulx_pix_XX[] = {
/* width height num_colors chars_per_pixel */
"    32    15       2            1",
/* colors */
". c #000000000000",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaa.aa.aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaa.aa.aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaa.aa.aaaaaaaaa.aaaaa.aaaaa",
"aaaaaaaa.aa.aaaaaaaaaa.aaa.aaaaaa",
"aaaaaaaa.aa.aaaaaaaaaaa.a.aaaaaaa",
"aaa......aa......aaaaaaa.aaaaaaaa",
"aaaaaaaa.aa.aaaaaaaaaaa.a.aaaaaaa",
"aaaaaaaa.aa.aaaaaaaaaa.aaa.aaaaaa",
"aaaaaaaa.aa.aaaaaaaaa.aaaaa.aaaaa",
"aaaaaaaa.aa.aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaa.aa.aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
};

/* XPM */
static char * mulx_pix[] = {
"32 15 9 1",
" 	c None",
".	c #804C48",
"+	c #000000",
"@	c #880000",
"#	c #000084",
"$	c #FFFFFF",
"%	c #501418",
"&	c #502420",
"*	c #181818",
"                                ",
"    .....   +@   +     # #      ",
"   .     @   +@ +@     # #      ",
"  .       @   ++@      # #      ",
"  @ $$    @   ++@      # #      ",
"  @ $$    @  +@ +@     # #      ",
"  @       @ +@   +    ## ##     ",
"  %       @        ##### #####  ",
"   %     @&           ## ##     ",
"    %%%%@*&&           # #      ",
"          *&&          # #      ",
"           *&&         # #      ",
"            *          # #      ",
"                       # #      ",
"                                "};
static char *divy_pix_xx[] = {
"32 15 3 1",
" 	c #FFFF00000000",
".	c #000000000000",
"X	s None",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"             .     XXXXXXXXXXXXXX",
"XXXX.XXXXXXXX.XXXXXXXXX..XXXXX..X",
"XXX...XXXXXXX.XXXXXXXXXX..XXX..XX",
"XX.....XXXXXX.XXXXXXXXXXX..X..XXX",
"X.......XXXXX.XXXXXXXXXXXX...XXXX",
"XXXX.XXXXXXXX.XXXXXXXXXXXXX.XXXXX",
"XXXX.XXXXX.......XXXXXXXXXX.XXXXX",
"XXXX.XXXXXX.....XXXXXXXXXXX.XXXXX",
"XXXX.XXXXXXX...XXXXXXXXXXXX.XXXXX",
"XXXX.XXXXXXXX.XXXXXXXXXXXX...XXXX",
"    .              XXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

/* XPM */
static char *divy_pix[] = {
"32 15 9 1",
" 	c None",
".	c #081D89",
"+	c #804C48",
"@	c #000000",
"#	c #880000",
"$	c #FFFFFF",
"%	c #501418",
"&	c #502420",
"*	c #181818",
"                                ",
"    .      +++++   @#   @#      ",
"   ...    +     #   @# @#       ",
"  .....  +       #   @@#   .    ",
" ....... # $$    #   @#    .    ",
"    .    # $$    #  @#     .    ",
"    .    #       # @#      .    ",
"    .    %       #         .    ",
"    .     %     #&         .    ",
"    .      %%%%#*&&     ....... ",
"    .            *&&     .....  ",
"                  *&&     ...   ",
"                   *       .    ",
"                                ",
"                                "};
static char *divy_pix_kuik[] = {
/* width height num_colors chars_per_pixel */
"    32    15       2            1",
/* colors */
". c Black",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaa...aaaaaaaaaa.aaaaa.aaaaaa",
"aaaaaa.....aaaaaaaaaa.aaa.aaaaaaa",
"aaaaa.......aaaaaaaaaa.a.aaaaaaaa",
"aaaaaaaa.aaaaaaaaaaaaa.a.aaaaaaaa",
"aaaaaaaa.aaaaaaaaaaaaaa.aaaaaaaaa",
"aaaaaaaa.aaaaaaaaaaaaaa.aaaaaaaaa",
"aaaaa.......aaaaaaaaaaa.aaaaaaaaa",
"aaaaaa.....aaaaaaaaaaaa.aaaaaaaaa",
"aaaaaaa...aaaaaaaaaaaaa.aaaaaaaaa",
"aaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
};

/* XPM */
static char *muly_pix_xxx[] = {
"32 15 3 1",
" 	s None",
".	c #000000000000",
"X	c #FFFF00000000",
"                                 ",
"   .........                     ",
"    .......            ..     .. ",
"     .....              ..   ..  ",
"      ...                .. ..   ",
"XXXXXXX.XXXXXXXXX         ...    ",
".......X.........          .     ",
"XXXXXXX.XXXXXXXXX          .     ",
"      ...                  .     ",
"     .....                 .     ",
"    .......               ...    ",
"   .........                     ",
"                                 ",
"                                 ",
"                                 ",
};
static char *muly_pix[] = {
"32 15 9 1",
" 	c None",
".	c #804C48",
"+	c #000000",
"@	c #880000",
"#	c #FFFFFF",
"$	c #081D89",
"%	c #501418",
"&	c #502420",
"*	c #181818",
"                                ",
"    .....   +@   +@             ",
"   .     @   +@ +@              ",
"  .       @   ++@               ",
"  @ ##    @   +@        $       ",
"  @ ##    @  +@        $$$      ",
"  @       @ +@    $$$$$$$$$$$$$ ",
"  %       @                     ",
"   %     @&       $$$$$$$$$$$$$ ",
"    %%%%@*&&           $$$      ",
"          *&&           $       ",
"           *&&                  ",
"            *                   ",
"                                ",
"                                "};

static char *muly_pix_kuik[] = {
/* width height num_colors chars_per_pixel */
"    32    15        2            1",
/* colors */
". c Black",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaa.aaaaaaaaaasaaaaasaaaaaa",
"aaaaaaaaa.aaaaaaaaaaa.aaa.aaaaaaa",
"aaa.............aaaaaa.a.aaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaa",
"aaa.............aaaaaaa.aaaaaaaaa",
"aaaaaaaaa.aaaaaaaaaaaaa.aaaaaaaaa",
"aaaaaaaaa.aaaaaaaaaaaaasaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
};


static char *script_pix_xxx[] = {
/* width height num_colors chars_per_pixel */
"    32   15        2            1",
/* colors */
". c #000000000000",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"a...aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
".aaa.aaaaaaaaaaaaaa.aaaaaaaaa.aaa",
".aaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaa",
".aaaaaa...aa.a..aa..aaa....a....a",
"a...aa.aaa.a..aa.aa.aaa.aaa.a.aaa",
"aaaa.a.aaaaa.aaaaaa.aaa.aaa.a.aaa",
"aaaa.a.aaaaa.aaaaaa.aaa.aaa.a.aaa",
".aaa.a.aaa.a.aaaaaa.aaa....aa.aa.",
"a...aaa...aa.aaaaa...aa.aaaaaa..a",
"aaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
};

/* XPM */
static char * script_pix[] = {
"32 15 5 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"@	c #3148C6",
"#	c #E82727",
"                                ",
"    .........                   ",
"   .+.++++++.         @@ @@     ",
"  .++.+++++@@@@      @#####@    ",
" .+++.++@+@+.  @    @ ##### @   ",
" .....++@@++.   @  @#########@  ",
" .++++++@@@+.      @####@####@  ",
" .++++++++++.       ###@@@###   ",
" .++++++++++. @@@  @####@####@  ",
" .++++++@+++.  @@  @#########@  ",
" .+++++++@++. @ @   @ ##### @   ",
" .++++++++@@@@       @#####@    ",
" .++++++++++.         @@ @@     ",
" ............                   ",
"                                "};
static char *grid_pix_xxx[] = {
/* width height num_colors chars_per_pixel */
"    32   15        2            1",
/* colors */
". c #000000000000",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaa.aaaa.aaaa.aaaaaaaaaaaa",
"aaaaaaa.................aaaaaaaaa",
"aaaaaaaaaa.aaaa.aaaa.aaaaaaaaaaaa",
"aaaaaaaaaa.aaaa.aaaa.aaaaaaaaaaaa",
"aaaaaaa.................aaaaaaaaa",
"aaaaaaaaaa.aaaa.aaaa.aaaaaaaaaaaa",
"aaaaaaaaaa.aaaa.aaaa.aaaaaaaaaaaa",
"aaaaaaa.................aaaaaaaaa",
"aaaaaaaaaa.aaaa.aaaa.aaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",

};

/* XPM */
static char * grid_pix[] = {
"32 15 2 1",
" 	c None",
".	c #000000",
"                                ",
"   .    .    .    .    .    .   ",
"  ............................  ",
"   .    .    .    .    .    .   ",
"   .    .    .    .    .    .   ",
"  ............................  ",
"   .    .    .    .    .    .   ",
"   .    .    .    .    .    .   ",
"  ............................  ",
"   .    .    .    .    .    .   ",
"   .    .    .    .    .    .   ",
"  ............................  ",
"   .    .    .    .    .    .   ",
"                                ",
"                                "};
static char *grid_gray_pix[] = {
/* width height num_colors chars_per_pixel */
"    32   15        2            1",
/* colors */
". c #000000000000",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaaa",
"aaaaaaaaaa.aaaaaaaaa.aaaaaaaaaaaa",
"aaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaaa",
"aaaaaaaaaa.aaaaaaaaa.aaaaaaaaaaaa",
"aaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",

};

static char *blue_pix[] = {
/* width height num_colors chars_per_pixel */
"    32   15        2            1",
/* colors */
". c blue",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaaa",
"aaaaaaaaaa.aaaaaaaaa.aaaaaaaaaaaa",
"aaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaaa",
"aaaaaaaaaa.aaaaaaaaa.aaaaaaaaaaaa",
"aaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",

};

static char *red_pix[] = {
/* width height num_colors chars_per_pixel */
"    32   15        2            1",
/* colors */
". c red",
"a s None",
/* pixels */
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaa",
"aaaaaaaaaa.aaaaaaaaa.aaaaaaaaaaa",
"aaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaa",
"aaaaaaaaaa.aaaaaaaaa.aaaaaaaaaaa",
"aaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaa",
"aaaaaaa.a.a.a.a.a.a.a.a.aaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",

};

/* XPM */
static char * au_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                                ",
"          ..    .    .          ",
"         .  .   .    .          ",
"        .    .  .    .          ",
"        .    .  .    .          ",
"        ......  .    .          ",
"        .    .  .    .          ",
"        .    .  .    .          ",
"        .    .  .    .          ",
"        .    .   ....           ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * bc_xpm[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"X	c blue",
"                                ",
"                                ",
"                                ",
"        ......    ....          ",
"        .     .  .    .         ",
"        .     . .               ",
"        .     . .               ",
"        ......  .               ",
"        .     . .               ",
"        .     . .               ",
"    XXXX.XXX  .  .   .          ",
" XX     ......    ....     XXXX ",
"             XXXX      XXXX     ",
"                 XXXXXX         ",
"                                "};
/* XPM */
static char * bookm_xpm_xxx[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                    .           ",
"  ....              .     .   . ",
"  .   .             .     .. .. ",
"  .   .  ...   ...  .  .  . . . ",
"  .   . .   . .   . . .   . . . ",
"  ....  .   . .   . ..    . . . ",
"  .   . .   . .   . . .   .   . ",
"  .   . .   . .   . . .   .   . ",
"  .   . .   . .   . . .   .   . ",
"  ....   ...   ...  .  .  .   . ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * bookm_xpm[] = {
"32 15 5 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"@	c #E03333",
"#	c #AA1616",
"   ....                         ",
"   .++.                         ",
"   .++.                         ",
"   ....              ..         ",
"                   ..@@.        ",
"   ....          ..@@@##.       ",
"   .++.        ..@@@##..        ",
"   .++.      ..@@@##..          ",
"   ....    ..@@@##..            ",
"          ..@@##..              ",
"   ....  ....#..                ",
"   .++. ......                  ",
"   .++.                         ",
"   ....                         ",
"                                "};
/* XPM */
static char * cp_xpm[] = {
"32 15 5 1",
" 	s None",
".	c #000000",
"a     c #ff0000",
"b     c #ffff00",
"x     c #ffffff",
" ...........                    ",
" ..aaaaaa...                    ",
" ..aabbaa...                    ",
" ..aabbaa...                    ",
" ..aaaaaa...     ...   ....     ",
" ...........    .   .  .   .    ",
" xxxxxxxxxxx    .      .   .    ",
" xxx.....xxx    .      ....     ",
" xx.x...x.xx    .      .        ",
" x.x.xxx.x.x    .   .  .        ",
" x.x.xxx.x.x     ...   .        ",
" x.x.xxx.x.x                    ",
" xx.x...x.xx                    ",
" xxx.....xxx                    ",
" xxxxxxxxxxx                    "};
/* XPM */
static char * cpold_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"     .....                      ",
"    .     .                     ",
"   .  ...  .      ...  ....     ",
"  .  .   .  .    .   . .   .    ",
"  . .     . .    .     .   .    ",
"  . .     . .    .     ....     ",
"  . .     . .    .     .        ",
"  .  .   .  .    .   . .        ",
"   .  ...  .      ...  .        ",
"    .     .                     ",
"     .....                      ",
"                                ",
"                                "};
/* XPM */
static char * cpm_xpm[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"x    c #ffffff",
"xxxxxxxxxxxxxxx                 ",
"xxxxxxxxxxxxxxx                 ",
"xxxxx.....xxxxx                 ",
"xxxx.xxxxx.xxxx                 ",
"xxx.xx...xx.xxx ...  ...  .    .",
"xx.xx.xxx.xx.xx.   . .  . ..  ..",
"xx.x.xxxxx.x.xx.     .  . . .. .",
"xx.x.xxxxx.x.xx.     ...  . .. .",
"xx.x.xxxxx.x.xx.     .    .    .",
"xx.xx.xxx.xx.xx.   . .    .    .",
"xxx.xx...xx.xxx ...  .    .    .",
"xxx.xxxxxx.xxxx                 ",
"xxxxx.....xxxxx                 ",
"xxxxxxxxxxxxxxx                 ",
"xxxxxxxxxxxxxxx                 "};
/* XPM */
static char * cpm1_xpm[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"x     c #ffffff",
"xxxxxxxxxxxxxxx                 ",
"xxxx.......xxxx                 ",
"xxx.xxxxxxx.xxx                 ",
"xx.xx.....xx.xx                 ",
"x.xx.xxxxx.xx.x ...  ...  .    .",
"x.x.xx...xx.x.x.   . .  . ..  ..",
"x.x.x.xxx.x.x.x.     .  . . .. .",
"x.x.x.xxx.x.x.x.     ...  . .. .",
"x.x.x.xxx.x.x.x.     .    .    .",
"x.x.xx...xx.x.x.   . .    .    .",
"x.xx.xxxxx.xx.x ...  .    .    .",
"xx.xx.....xx.x                  ",
"xxx.xxxxxxx.xxx                 ",
"xxxx.......xxxx                 ",
"xxxxxxxxxxxxxxx                 "};
/* XPM */
static char * crop_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"     ....                       ",
"    .    .                      ",
"   .        . .  ...   . ..     ",
"   .        ..  .   .  ..  .    ",
"   .        .   .   .  .   .    ",
"   .        .   .   .  .   .    ",
"   .        .   .   .  .   .    ",
"    .    .  .   .   .  ..  .    ",
"     ....   .    ...   . ..     ",
"                       .        ",
"                       .        ",
"                       .        ",
"                                "};
/* XPM */
static char * down_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                                ",
"    ...                         ",
"    .  .                        ",
"    .   .  ...  .   . . ..      ",
"    .   . .   . .   . ..  .     ",
"    .   . .   . . . . .   .     ",
"    .   . .   . . . . .   .     ",
"    .  .  .   . . . . .   .     ",
"    ...    ...   . .  .   .     ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * down_xpm[] = {
"32 15 4 1",
" 	c None",
".	c #000000",
"+	c #0000FF",
"@	c #FF0000",
"                                ",
"                                ",
"                    ...         ",
" ++@++++++++++      .  .        ",
" ++@++++++++++      .   . .   . ",
"   @         +      .   . .   . ",
"   @    @ +++++++   .   . ..  . ",
"   @    @  +++++    .   . . . . ",
"   @    @   +++  @  .   . .  .. ",
"   @    @    +   @  .   . .   . ",
"   @   @@ @     @@  ....  .   . ",
"  @ @  @@ @     @@              ",
"  @ @  @@ @@ @ @  @             ",
" @   @@@ @ @@@@   @@            ",
"                                "};
/* XPM */
static char * dr_xpm[] = {
"32 15 3 1",
" 	s None",
".	c blue",
"X	c #000000",
"                                ",
"                                ",
"    X                           ",
"   X.X        XXXX    XXXXX     ",
"  X . X       X   X   X    X    ",
"    .         X    X  X    X    ",
"    .         X    X  X    X    ",
"    .         X    X  XXXXX     ",
"    .         X    X  X  X      ",
"    .         X    X  X   X     ",
"    .    X    X   X   X    X    ",
"    .     X   XXXX    X     X   ",
"    .......X                    ",
"          X                     ",
"         X                      "};
/* XPM */
static char * ft_xpm[] = {
"32 15 3 1",
" 	s None",
".	c #FFFF00000000",
"X	c #000000000000",
"                                ",
"  .                             ",
"  ..                            ",
"  ...                           ",
"  .....         XXXXX XXXXXXX   ",
"  .......       X        X      ",
"  .........     X        X      ",
"  ............. XXXX     X      ",
"  ..........    X        X      ",
"  ........      X        X      ",
"  .....         X        X      ",
"  ...           X        X      ",
"  ..                            ",
"  .                             ",
"                                "};
/* XPM */
static char * full_xpm_xxx[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                   ..    ..     ",
"     .....          .     .     ",
"     .              .     .     ",
"     .              .     .     ",
"     .              .     .     ",
"     ....  .    .   .     .     ",
"     .     .    .   .     .     ",
"     .     .    .   .     .     ",
"     .     .   ..   .     .     ",
"     .      ... .  ...   ...    ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char *full_xpm[] = {
"32 15 9 1",
" 	c None",
".	c #804C48",
"+	c #081D89",
"@	c #880000",
"#	c #FFFFFF",
"%	c #4E2322",
"&	c #000000",
"*	c #502420",
"                                ",
"            .....  ++  ++       ",
"           .      ++  ++        ",
"          .      ++ @++         ",
"          @ ##  ++  ++          ",
"          @ #  ++  ++           ",
"          @   ++  ++@           ",
"          @  ++  ++ @           ",
"           %++  ++  @           ",
"           ++% ++  @*           ",
"          ++  ++%%@&**          ",
"         ++  ++     &**         ",
"        ++  ++       &**        ",
"       ++  ++         &         ",
"                                "};

/* XPM */
static char * mouse_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                                ",
" .   .                          ",
" .. ..                          ",
" . . .  ...  .   .  ....  ...   ",
" . . . .   . .   . .     .   .  ",
" .   . .   . .   .  ...  .....  ",
" .   . .   . .  ..     . .      ",
" .   .  ...   .. . ....   ...   ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * next_xpm_xxx[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"a	c blue",
"                                ",
"                                ",
"                      .   aaaa  ",
"  .   .               .   a   a ",
"  ..  .               .   aaaa  ",
"  ..  .  ...  .   . ..... a  a  ",
"  . . . .   .  . .    .   a   a ",
"  .  .. .....   .     .         ",
"  .  .. .      . .    .         ",
"  .   . .     .   .   .         ",
"  .   .  ... .     .   ..       ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * next_xpm[] = {
"32 15 5 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"@	c #1939EA",
"#	c #3496D8",
"                                ",
"  .............  .............  ",
"  .+++++++++++.  .+++++++++++.  ",
"  .+++++++++++.  .+++@+++++++.  ",
"  .+++++++++++.  .+++@@++++++.  ",
"  .+++++++++++.  .+++@#@+++++.  ",
"  .+++++++@@@@@@@@@@@@##@++++.  ",
"  .++++++++##############@+++.  ",
"  .+++++++@@@@@@@@@@@###@++++.  ",
"  .+++++++++++.  .+++@#@+++++.  ",
"  .+++++++++++.  .+++@@++++++.  ",
"  .+++++++++++.  .+++@+++++++.  ",
"  .+++++++++++.  .+++++++++++.  ",
"  .............  .............  ",
"                                "};
/* XPM */
static char * pclpm_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"         ..           .         ",
"   ...    .           .         ",
"  .   .   .         .....       ",
"  .       .           .         ",
"  .       .           .         ",
"  .       .                     ",
"  .       .     .............   ",
"  .       .                     ",
"  .   .   .                     ",
"   ...   ...       .......      ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * pclpm_xpm[] = {
"32 15 4 1",
" 	c None",
".	c #FF0000",
"+	c #0000FF",
"@	c #000000",
"                                ",
"  ...... ++++++         @@      ",
"  .    . +    +         @@      ",
"  .    . +    +         @@      ",
"  .    . +    +      @@@@@@@@   ",
"  .    . +    +      @@@@@@@@   ",
"  ...... ++++++         @@      ",
"                        @@      ",
"  ++++++ ......         @@      ",
"  +    + .    .                 ",
"  +    + .    .      @@@@@@@@   ",
"  +    + .    .      @@@@@@@@   ",
"  +    + .    .                 ",
"  ++++++ ......                 ",
"                                "};
/* XPM */
static char * pclm_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"           ..                   ",
"     ...    .                   ",
"    .   .   .                   ",
"    .       .                   ",
"    .       .                   ",
"    .       .   .......         ",
"    .       .                   ",
"    .       .                   ",
"    .   .   .                   ",
"     ...   ...                  ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * pclm_xpm[] = {
"32 15 3 1",
" 	c None",
"+	c #0000FF",
"@	c #000000",
"                                ",
"         ++++++                 ",
"         +    +                 ",
"         +    +                 ",
"         +    +                 ",
"         +    +                 ",
"         ++++++                 ",
"                                ",
"  ++++++                        ",
"  +    +                        ",
"  +    +             @@@@@@@@   ",
"  +    +             @@@@@@@@   ",
"  +    +                        ",
"  ++++++                        ",
"                                "};/* XPM */
static char * pclp_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"           ..                   ",
"     ...    .                   ",
"    .   .   .      .            ",
"    .       .      .            ",
"    .       .      .            ",
"    .       .   .......         ",
"    .       .      .            ",
"    .       .      .            ",
"    .   .   .      .            ",
"     ...   ...                  ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * pclp_xpm[] = {
"32 15 3 1",
" 	c None",
".	c #FF0000",
"@	c #000000",
"                                ",
"  ......                @@      ",
"  .    .                @@      ",
"  .    .                @@      ",
"  .    .             @@@@@@@@   ",
"  .    .             @@@@@@@@   ",
"  ......                @@      ",
"                        @@      ",
"         ......         @@      ",
"         .    .                 ",
"         .    .                 ",
"         .    .                 ",
"         .    .                 ",
"         ......                 ",
"                                "};
/* XPM */
static char * phase2d_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"        .                       ",
"  ....  .                       ",
"  .   . .                       ",
"  .   . .                       ",
"  .   . ....   ....  ....  ...  ",
"  ....  .   . .   . .     .   . ",
"  .     .   . .   .  ...  ..... ",
"  .     .   . .   .     . .     ",
"  .     .   . .  ..     . .     ",
"  .     .   .  .. . ....   ...  ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * pk_xpm[] = {
"32 15 3 1",
" 	s None",
".	c blue",
"X	c #000000",
"                                ",
"      .                         ",
"      .                         ",
"      .         XXXXX   X    X  ",
"     ..         X    X  X   X   ",
"     ..         X    X  X  X    ",
"    ...         X    X  X X     ",
" ...  .  .....  XXXXX   XX      ",
"      ....      X       X X     ",
"      ..        X       X  X    ",
"      ..        X       X   X   ",
"      .         X       X    X  ",
"      .                         ",
"                                ",
"                                "};
/* XPM */
static char * pl2d_xpm[] = {
"32 15 6 1",
" 	s None",
".	c #000000",
"X	c #0000FF",
"o	c #FF00FF",
"a	c #FF0000",
"b	c #FFFF00",
"                                ",
"  ...........                   ",
"  ...........                   ",
"  ...XXXXX...                   ",
"  ..XXoooXX..    ....  .        ",
"  .XXoaaaoXX.    .   . .        ",
"  .XoaabaaoX.    .   . .        ",
"  .XoabbbaoX.    ....  .        ",
"  .XoaabaaoX.    .     .        ",
"  .XXoaaaoXX.    .     .        ",
"  ..XXoooXX..    .     .....    ",
"  ...XXXXX...                   ",
"  ...........                   ",
"  ...........                   ",
"                                "};
/* XPM */
static char * cpm2d_xpm[] = {
"32 15 6 1",
" 	s None",
".	c #000000",
"X	c #0000FF",
"o	c #FF00FF",
"a	c #FF0000",
"b	c #FFFF00",
"                                ",
"  ...........                   ",
"  ...........                   ",
"  ...XXXXX...                   ",
"  ..XaaaaaX..   ...  ...  .    .",
"  .XaaaaaaaX.  .   . .  . ..  ..",
"  .XaaabaaaX.  .     .  . . .. .",
"  .XaabbbaaX.  .     ...  . .. .",
"  .XaaabaaaX.  .     .    .    .",
"  .XaaaaaaaX.  .   . .    .    .",
"  ..XaaaaaX..   ...  .    .    .",
"  ...XXXXX...                   ",
"  ...........                   ",
"  ...........                   ",
"                                "};
/* XPM */
static char * planedn_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"  ............                  ",
"  .          .  .....           ",
"  .          .  .    .          ",
"  .          .  .     .  . ..   ",
"  .          .  .     .  ..  .  ",
"  .          .  .     .  .   .  ",
"  .          .  .     .  .   .  ",
"  .          .  .     .  .   .  ",
"  .          .  .    .   .   .  ",
"  .          .  .....    .   .  ",
"  ............                  ",
"                                ",
"                                "};
/* XPM */
static char * planedn_xpm[] = {
"32 15 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"                                ",
"   ...........                  ",
"  .+++++++++..                  ",
" ...........+.  .....           ",
" .+++++++++.+.  .    .          ",
" .++++.++++.+.  .     .  . ..   ",
" .++++.++++.+.  .     .  ..  .  ",
" .++++.++++.+.  .     .  .   .  ",
" .++.+.+.++.+.  .     .  .   .  ",
" .+++...+++.+.  .     .  .   .  ",
" .++++.++++.+.  .    .   .   .  ",
" .+++++++++.+.  .....    .   .  ",
" .+++++++++..                   ",
" ...........                    ",
"                                "};/* XPM */
static char * planer_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"  ............                  ",
"  .          .                  ",
"  .          .    ....          ",
"  .          .    .   .         ",
"  .          .    .   .         ",
"  .          .    ....          ",
"  .          .    . .           ",
"  .          .    .  .          ",
"  .          .    .   .         ",
"  .          .                  ",
"  ............                  ",
"                                ",
"                                "};
/* XPM */
static char * planer_xpm[] = {
"32 15 4 1",
" 	c None",
".	c #000000",
"+	c #000084",
"@	c #FFFFFF",
"                                ",
"    ..........     +++          ",
"   .@@@@@@@@..   +++++++      + ",
"  .@@@@@@@@.@.   ++   ++++   ++ ",
" ..........@@.  ++      +++ +++ ",
" .@@@@@@@@.@@.  ++       ++++++ ",
" .@@@@@@@@.@@.  ++        +++++ ",
" .@@@@@@@@.@@.  ++       ++++++ ",
" .@@@@@@@@.@@.  ++      +++++++ ",
" .@@@@@@@@.@@.   ++    ++++++++ ",
" .@@@@@@@@.@@.   +++            ",
" .@@@@@@@@.@.     ++++          ",
" .@@@@@@@@..       +++          ",
" ..........                     ",
"                                "};/* XPM */
static char * planeup_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"  ............                  ",
"  .          .  .    .          ",
"  .          .  .    .          ",
"  .          .  .    .  . ..    ",
"  .          .  .    .  ..  .   ",
"  .          .  .    .  .   .   ",
"  .          .  .    .  .   .   ",
"  .          .  .    .  .   .   ",
"  .          .  .    .  ..  .   ",
"  .          .   ....   . ..    ",
"  ............          .       ",
"                        .       ",
"                        .       "};
/* XPM */
static char * planeup_xpm[] = {
"32 15 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"                                ",
"   ...........                  ",
"  .+++++++++..                  ",
" ...........+.  .    .          ",
" .+++++++++.+.  .    .          ",
" .+++++++++.+.  .    .  . ..    ",
" .++++.++++.+.  .    .  ..  .   ",
" .+++...+++.+.  .    .  .   .   ",
" .++.+.+.++.+.  .    .  .   .   ",
" .++++.++++.+.  .    .  .   .   ",
" .++++.++++.+.  .    .  ..  .   ",
" .++++.++++.+.   ....   . ..    ",
" .+++++++++..           .       ",
" ...........            .       ",
"                        .       "};
/* XPM */
static char * planeu_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"  ............                  ",
"  .          .                  ",
"  .          .    .   .         ",
"  .          .    .   .         ",
"  .          .    .   .         ",
"  .          .    .   .         ",
"  .          .    .   .         ",
"  .          .    .   .         ",
"  .          .     ...          ",
"  .          .                  ",
"  ............                  ",
"                                ",
"                                "};
/* XPM */
static char * planeu_xpm[] = {
"32 15 4 1",
" 	c None",
".	c #000000",
"+	c #000084",
"@	c #FFFFFF",
"                                ",
"    ..........           +++    ",
"   .@@@@@@@@..  +      +++++++  ",
"  .@@@@@@@@.@.  ++   ++++   ++  ",
" ..........@@.  +++ +++      ++ ",
" .@@@@@@@@.@@.  ++++++       ++ ",
" .@@@@@@@@.@@.  +++++        ++ ",
" .@@@@@@@@.@@.  ++++++       ++ ",
" .@@@@@@@@.@@.  +++++++      ++ ",
" .@@@@@@@@.@@.  ++++++++    ++  ",
" .@@@@@@@@.@@.             +++  ",
" .@@@@@@@@.@.            ++++   ",
" .@@@@@@@@..             +++    ",
" ..........                     ",
"                                "};
/* XPM */
static char * plplus_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                                ",
"       ....  .                  ",
"       .   . .       .          ",
"       .   . .       .          ",
"       ....  .     .....        ",
"       .     .       .          ",
"       .     .       .          ",
"       .     .....              ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * pl_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"                                ",
"          .....   .             ",
"          .    .  .             ",
"          .    .  .             ",
"          .    .  .             ",
"          .....   .             ",
"          .       .             ",
"          .       .             ",
"          .       .             ",
"          .       .....         ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * prev_xpm_zzz[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"a	c blue",
"                                ",
"                                ",
"                          aaaa  ",
"  ....                    a   a ",
"  .   .                   aaaa  ",
"  .   . . ..   ...  .   . a  a  ",
"  ....  ..    .   . .   . a   a ",
"  .     .     .....  . .        ",
"  .     .     .      . .        ",
"  .     .     .       .         ",
"  .     .      ...    .         ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * prev_xpm[] = {
"32 15 5 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"@	c #1939EA",
"#	c #3496D8",
"                                ",
"  .............  .............  ",
"  .+++++++++++.  .+++++++++++.  ",
"  .+++++++@+++.  .+++++++++++.  ",
"  .++++++@@+++.  .+++++++++++.  ",
"  .+++++@#@+++.  .+++++++++++.  ",
"  .++++@##@@@@@@@@@@@@+++++++.  ",
"  .+++@##############++++++++.  ",
"  .++++@###@@@@@@@@@@@+++++++.  ",
"  .+++++@#@+++.  .+++++++++++.  ",
"  .++++++@@+++.  .+++++++++++.  ",
"  .+++++++@+++.  .+++++++++++.  ",
"  .+++++++++++.  .+++++++++++.  ",
"  .............  .............  ",
"                                "};
/* XPM */
static char * redo_xpm_xxx[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"a	c blue",
"                                ",
"                                ",
"                  .       aaaa  ",
"  ....            .       a   a ",
"  .   .           .       aaaa  ",
"  .   .  ...   ....  ...  a  a  ",
"  ....  .   . .   . .   . a   a ",
"  . .   ..... .   . .   .       ",
"  .  .  .     .   . .   .       ",
"  .  .  .     .   . .   .       ",
"  .   .  ...   ....  ...        ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * redo_xpm[] = {
"32 15 4 1",
" 	c None",
".	c #000000",
"+	c #000084",
"@	c #FFFFFF",
"                                ",
" .............     +++          ",
" .@@@@@@@@@@@.   +++++++      + ",
" .@@@@@@@@@@@.   ++   ++++   ++ ",
" .@@@@@@@@@@@.  ++      +++ +++ ",
" .@@@@@@@@@@@.  ++       ++++++ ",
" .@@@@@@@@@@@.  ++        +++++ ",
" .@@@@@@@@@@@.  ++       ++++++ ",
" .@@@@@@@@@@@.  ++      +++++++ ",
" .@@@@@@@@@@@.   ++    ++++++++ ",
" .@@@@@@@@@@@.   +++            ",
" .@@@@@@@@@@@.    ++++          ",
" .@@@@@@@@@@@.     +++          ",
" .............                  ",
"                                "};
/* XPM */
static char * rn_xpm_xxx[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"                                ",
"        .....   .    .          ",
"        .    .  .    .          ",
"        .    .  ..   .          ",
"        .    .  . .  .          ",
"        .....   .  . .          ",
"        . .     .   ..          ",
"        .  .    .   ..          ",
"        .   .   .    .          ",
"        .    .  .    .          ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * rn_xpm[] = {
"32 15 6 1",
" 	c None",
".	c #0D2A7A",
"+	c #41B7CC",
"@	c #000000",
"#	c #A6E1ED",
"$	c #FFFFFF",
"                                ",
"                                ",
"     ..........                 ",
"     .++++++++.  @@@@@   @    @ ",
"   ..........+.  @    @  @    @ ",
"   .########.+.  @    @  @@   @ ",
" ..........#.+.  @    @  @ @  @ ",
" .$$$$$$$$.#.+.  @@@@@   @  @ @ ",
" .$$$$$$$$.#.+.  @ @     @   @@ ",
" .$$$$$$$$.#...  @  @    @   @@ ",
" .$$$$$$$$.#.    @   @   @    @ ",
" .$$$$$$$$...    @    @  @    @ ",
" .$$$$$$$$.                     ",
" ..........                     ",
"                                "};
/* XPM */
static char * row_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"                                ",
"      ....                      ",
"      .   .                     ",
"      .   .   ...  .   .        ",
"      ....   .   . .   .        ",
"      . .    .   . . . .        ",
"      .  .   .   . . . .        ",
"      .   .  .   . . . .        ",
"      .    .  ...   . .         ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * row_xpm[] = {
"32 15 3 1",
" 	c None",
".	c #000000",
"+	c #1C45DB",
"                                ",
"                                ",
"                                ",
"          ....                  ",
"  +       .   .                 ",
"  +       .   .   ...  .   .    ",
"  +       ....   .   . .   .    ",
"  +       . .    .   . . . .    ",
"  +       .  .   .   . . . .    ",
"  +  +    .   .  .   . . . .    ",
"  +  +    .    .  ...   . .     ",
"  +  +  +                       ",
"++ +++++++++++++                ",
"                                ",
"                                "};
/* XPM */
static char * col_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"                     ..         ",
"         ...          .         ",
"        .   .         .         ",
"        .      ...    .         ",
"        .     .   .   .         ",
"        .     .   .   .         ",
"        .     .   .   .         ",
"        .   . .   .   .         ",
"         ...   ...   ...        ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * col_xpm[] = {
"32 15 3 1",
" 	c None",
".	c #1C45DB",
"+	c #000000",
"        .                       ",
"        .                       ",
"        .               ++      ",
"        .   +++          +      ",
"        .  +   +         +      ",
"        .  +      +++    +      ",
"        .  +     +   +   +      ",
"       ..  +     +   +   +      ",
"        .  +     +   +   +      ",
"        .  +   + +   +   +      ",
"     ....   +++   +++   +++     ",
"        .                       ",
" .......                        ",
"        .                       ",
"        .                       "};
/* XPM */
static char * rowcol_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"               .                ",
"       ....    .    ...         ",
"       .   .   .   .   .        ",
"       .   .   .   .            ",
"       ....    .   .            ",
"       . .     .   .            ",
"       .  .    .   .            ",
"       .   .   .   .   .        ",
"       .    .  .    ...         ",
"               .                ",
"               .                ",
"                                ",
"                                "};
/* XPM */
static char * rowcol_xpm[] = {
"32 15 3 1",
" 	c None",
".	c #1C45DB",
"+	c #000000",
"       .                        ",
"       .                        ",
"    ....                        ",
"       .  ++++          +++     ",
"  .    .  +   +        +   +    ",
"  . ....  +   +   +    +        ",
"  .    .  ++++    +    +        ",
"  .   ..  + +   +++++  +        ",
"  .    .  +  +    +    +        ",
"  . .  .  +   +   +    +   +    ",
"  . .  .  +    +        +++     ",
"  . .  .                        ",
".. .............                ",
"       .                        ",
"       .                        "};
/* XPM */
static char * rowcolperp_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"               .                ",
"               .                ",
"               .                ",
"               .                ",
"               .                ",
"               .                ",
"               .                ",
"               .                ",
"               .                ",
"     .....................      ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * scale_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"                      ..        ",
"   ...                 .        ",
"  .                    .        ",
"  .                    .        ",
"  .       ....  ....   .   ...  ",
"   ...   .     .   .   .  .   . ",
"      .  .     .   .   .  ..... ",
"      .  .     .   .   .  .     ",
"  .   .  .     .  ..   .  .   . ",
"   ...    ....  .. .  ...  ...  ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * twod_xx_xpm[] = {
"32 15 3 1",
" 	s None",
"X	c #000000",
".	c Red",
"                                ",
"                                ",
"        .....    .....          ",
"       .XXXXX.   .XXXX.         ",
"          XXX.X  .XXXXX.X       ",
"             .XX .XX   .XX      ",
"            .XXX .XX   .XX      ",
"           .XXX  .XX   .XX      ",
"          .XXX   .XX   .XX      ",
"         .XXX    .XX   .XX      ",
"        ......X  ......X        ",
"         XXXXXX   XXXXx         ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char *twod_x_xpm[] = {
/* width height num_colors chars_per_pixel */
"    32    15        4            1",
/* colors */
"  c None",
"a c #686c68",
"c c #f80000",
"d c #000000",
/* pixels */
"                                ",
"       cccccc    ccccccc        ",
"      cccccccc   cccccccc       ",
"     ccdddddccd  ccddddccc      ",
"       daaaaccd  ccdaaaaccd     ",
"       aa  ccdd  ccda  bccd     ",
"          ccdda  ccda  bccda    ",
"         ccdda   ccda  bccda    ",
"        ccdda    ccda  bccda    ",
"       ccdda     ccda  bccda    ",
"      cccccccc   cccccccccda    ",
"     cccccccccd  ccccccccdaa    ",
"       dddddddda   ddddddda     ",
"       aaaaaaaaa   aaaaaaa      ",
"                                "
};
/* XPM */
static char * twod_xpm[] = {
"32 15 3 1",
" 	c None",
".	c #FFFF00000000",
"X	c #000000000000",
"                                ",
"       ......    .......        ",
"      ........   ........       ",
"     .. XXXX..   ..XXXX...      ",
"       XXXXX..X  ..XXXXX..      ",
"      XX   ..XX  ..X    ..X     ",
"          .. XX  ..X    ..X     ",
"         .. XX   ..X    ..X     ",
"        .. XX    ..X    ..X     ",
"       .. XX     ..X   ...X     ",
"      ........   .........X     ",
"     .........   ........XX     ",
"       XXXXXXXX   XXXXXXXXX     ",
"      XXXXXXXXX   XXXXXXXX      ",
"                                "};

/* XPM */
static char * twod_xpm__[] = {
"33 16 4 1",
" 	c None",
".	c #0000FF",
"+	c #000000",
"@	c #FF0000",
"                                 ",
"      .......    .........       ",
"     ..++++..+   ..........      ",
"     .+++++..++  ..++++++..+     ",
"      +++  ..++  ..+++++++.++    ",
"           ..++  ..++     .++    ",
"          ..+++  ..++     .++    ",
"        ...++++  ..++     .++    ",
"       ..++++    ..++     .++    ",
"      @.+++++    .@++     @++    ",
"     @@++++      @@++    @@++    ",
"     @@@@@@@@    @@++   @@+++    ",
"     @@@@@@@@+   @@@@@@@@++++    ",
"      +++++++++   ++++++++++     ",
"       ++++++++    ++++++++      ",
"                                 "};

/* XPM */
static char * uncrop_xpm__[] = {
"32 15 3 1",
" 	s None",
".	c #000000000000",
"X	c #FFFF00000000",
"                                ",
"                                ",
"     ....                       ",
"    .    .                      ",
"   .        . .  ...   . ..     ",
"   .        ..  .   .  ..  .    ",
"   .        .   .   .  .   .    ",
"  XXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"  XXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"    .    .  .   .   .  ..  .    ",
"     ....   .    ...   . ..     ",
"                       .        ",
"                       .        ",
"                       .        ",
"                                "};
/* XPM */
static char * uncrop_xpm[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"x	c #0000FF",
"                                ",
"                                ",
"     ....          xx  xx       ",
"    .    .        xx  xx        ",
"   .        . .  xx. xx. ..     ",
"   .        ..  xx  xx ..  .    ",
"   .        .  xx  xx  .   .    ",
"   .        . xx. xx.  .   .    ",
"   .        .xx .xx .  .   .    ",
"    .    .  xx  xx  .  ..  .    ",
"     ....  xx  xx...   . ..     ",
"          xx  xx       .        ",
"         xx  xx        .        ",
"        xx  xx         .        ",
"                                "};
/* XPM */
static char * undo_xpm_xxx[] = {
"32 15 3 1",
" 	s None",
".	c #000000",
"a	c blue",
"                                ",
"                                ",
"                  .       aaaa  ",
"  .   .           .       a   a ",
"  .   .           .       aaaa  ",
"  .   . . ..   ....  ...  a  a  ",
"  .   . ..  . .   . .   . a   a ",
"  .   . .   . .   . .   .       ",
"  .   . .   . .   . .   .       ",
"  .   . .   . .   . .   .       ",
"   ...  .   .  ....  ...        ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * undo_xpm[] = {
"32 15 4 1",
" 	c None",
".	c #000000",
"+	c #000084",
"@	c #FFFFFF",
"                                ",
" .............           +++    ",
" .@@@@@@@@@@@.  +      +++++++  ",
" .@@@@@@@@@@@.  ++   ++++   ++  ",
" .@@@@@@@@@@@.  +++ +++      ++ ",
" .@@@@@@@@@@@.  ++++++       ++ ",
" .@@@@@@@@@@@.  +++++        ++ ",
" .@@@@@@@@@@@.  ++++++       ++ ",
" .@@@@@@@@@@@.  +++++++      ++ ",
" .@@@@@@@@@@@.  ++++++++    ++  ",
" .@@@@@@@@@@@.             +++  ",
" .@@@@@@@@@@@.           ++++   ",
" .@@@@@@@@@@@.           +++    ",
" .............                  ",
"                                "};
/* XPM */
static char * up_xpm__[] = {
"32 15 2 1",
" 	s None",
".	c #000000",
"                                ",
"                                ",
"          .   .                 ",
"          .   .                 ",
"          .   . ....            ",
"          .   . .   .           ",
"          .   . .   .           ",
"          .   . .   .           ",
"          .   . .   .           ",
"           ...  ....            ",
"                .               ",
"                .               ",
"                .               ",
"                                ",
"                                "};
/* XPM */
static char * up_xpm[] = {
"32 15 4 1",
" 	c None",
".	c #000000",
"+	c #FF0000",
"@	c #0000FF",
"                                ",
"                                ",
"              @     .   .       ",
"   +         @@@    .   .       ",
"   +        @@@@@   .   . ...   ",
"   +       @@@@@@@  .   . .  .  ",
"   +    +     @     .   . .   . ",
" @@+@@@@+@@@@@@     .   . .   . ",
" @@+@@@@+@@@@@@  +  .   . .   . ",
"   +    +        +  .   . .   . ",
"   +   ++ +     ++   ...  ....  ",
"  + +  ++ +     ++        .     ",
"  + +  ++ ++ + +  +       .     ",
" +   +++ + ++++   ++      .     ",
"                                "};
/* XPM */
static char * wn_xpm[] = {
"32 15 4 1",
" 	s None",
".	c #0000FF",
"X	c #FF0000",
"o	c #000000",
"  ...                           ",
"  X   .                         ",
"  XX    .                       ",
"  XXX    .      o     o         ",
"  XXXXX    .    o     o         ",
"  XXXXXXXX  .   o     o         ",
"  XXXXXXXXXX .  o     o  o ooo  ",
"  XXXXXXXXXXXX  o  o  o  oo   o ",
"  XXXXXXXXX     o o o o  o    o ",
"  XXXXXXXX      oo   oo  o    o ",
"  XXXXX         oo   oo  o    o ",
"  XXX           o     o  o    o ",
"  XX                            ",
"  X                             ",
"                                "};
/* XPM */
static char * zoomrggg_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                                ",
"  .....                   ....  ",
"      .                   .   . ",
"     .   ...   ...  .. .  .   . ",
"    .   .   . .   . . . . ....  ",
"   .    .   . .   . . . . . .   ",
"  .     .   . .   . . . . .  .  ",
"  .     .   . .   . .   . .   . ",
"  .....  ...   ...  .   . .   . ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * zoomr_xpm[] = {
"32 15 8 1",
" 	c None",
".	c #804C48",
"+	c #000084",
"@	c #880000",
"#	c #FFFFFF",
"$	c #501418",
"%	c #502420",
"&	c #181818",
"                                ",
"    .....        ++++           ",
"   .     @     ++++++++      +  ",
"  .       @    ++    ++++   ++  ",
"  @ ##    @   ++       +++ +++  ",
"  @ ##    @   ++        ++++++  ",
"  @       @   ++         +++++  ",
"  $       @   ++        ++++++  ",
"   $     @%   ++       +++++++  ",
"    $$$$@&%%   ++     ++++++++  ",
"          &%%   ++              ",
"           &%%   +++            ",
"            &      +++          ",
"                                ",
"                                "};
/* XPM */
static char * zoomugg_xpm[] = {
"32 15 2 1",
" 	s None",
".	c #000000000000",
"                                ",
"                                ",
"                                ",
"  .....                   .   . ",
"      .                   .   . ",
"     .   ...   ...  .. .  .   . ",
"    .   .   . .   . . . . .   . ",
"   .    .   . .   . . . . .   . ",
"  .     .   . .   . . . . .   . ",
"  .     .   . .   . .   . .   . ",
"  .....  ...   ...  .   .  ...  ",
"                                ",
"                                ",
"                                ",
"                                "};
/* XPM */
static char * zoomu_xpm[] = {
"32 15 8 1",
" 	c None",
".	c #804C48",
"+	c #000084",
"@	c #880000",
"#	c #FFFFFF",
"$	c #501418",
"%	c #502420",
"&	c #181818",
"                                ",
"    .....              ++++     ",
"   .     @    +      ++++++++   ",
"  .       @   ++   ++++    ++   ",
"  @ ##    @   +++ +++       ++  ",
"  @ ##    @   ++++++        ++  ",
"  @       @   +++++         ++  ",
"  $       @   ++++++        ++  ",
"   $     @%   +++++++       ++  ",
"    $$$$@&%%  ++++++++     ++   ",
"          &%%             +++   ",
"           &%%          ++++    ",
"            &           +++     ",
"                                ",
"                                "};
/* XPM */
static char * xterm_xpm[] = {
"32 15 3 1",
" 	s None",
".	c #000000000000",
"a	c blue",
"                                ",
"                                ",
"   aaaaaaaaaaaaaaaaaaaaaaaaaa   ",
"   a                        a   ",
"   a........................a   ",
"   .                        .   ",
"   .                        .   ",
"   .                        .   ",
"   .                        .   ",
"   .                        .   ",
"   .                        .   ",
"   .                        .   ",
"   ..........................   ",
"                                ",
"                                "};

/* XPM */
static char * empty_xpm[] = {
"32 15 1 1",
" 	s None",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};




/* XPM */
static char * mouse_pos_xpm[] = {
"16 16 6 1",
" 	c None",
"+	c blue",
"X	c black",
"o	c white",
".	c darkred",
"a	c darkgreen",
"   +      . .   ",
"  ++     .   .  ",
"   +     .   .  ",
"   +        .   ",
"   +  X    .    ",
"      XX .....  ",
"      XoX       ",
" aa   XooX      ",
"a  a  XoooX     ",
"   a  XooooX    ",
" aa   XoooooX   ",
"   a  XoooXXXX  ",
"a  a  XoXooX    ",
" aa   XX XooX   ",
"      X  XooX   ",
"          XooX  "};

/* XPM */
static char * mouse_zoomxy_xpm[] = {
/* width height num_colors chars_per_pixel */
"16 16 7 1",
/* colors */
" 	c None",
".	c #804c48",
"X	c #880000",
"o	c white",
"O	c #501418",
"+	c #502420",
"@	c #181818",
/* pixels */
"                ",
"                ",
"    .....       ",
"   .     X      ",
"  .       X     ",
"  X oo    X     ",
"  X oo    X     ",
"  X       X     ",
"  O       X     ",
"   O     X+     ",
"    OOOOX@++    ",
"          @++   ",
"           @++  ",
"            @   ",
"                ",
"                "};
/* XPM */
static char * mouse_zoomx_xpm[] = {
/* width height num_colors chars_per_pixel */
"16 16 9 1",
/* colors */
" 	c None",
".	c #804c48",
"X	c black",
"o	c #888888",
"O	c #880000",
"+	c white",
"@	c #501418",
"#	c #502420",
"$	c #181818",
/* pixels */
"                ",
"                ",
"  .....   Xo   X",
" .     O   Xo Xo",
".       O   XXo ",
"O ++    O   XXo ",
"O ++    O  Xo Xo",
"O       O Xo   X",
"@       O       ",
" @     O#       ",
"  @@@@O$##      ",
"        $##     ",
"         $##    ",
"          $     ",
"                ",
"                "};
/* XPM */
static char * mouse_zoomy_xpm[] = {
/* width height num_colors chars_per_pixel */
"16 16 9 1",
/* colors */
" 	c None",
".	c #804c48",
"X	c black",
"o	c #880000",
"O	c #888888",
"+	c white",
"@	c #501418",
"#	c #502420",
"$	c #181818",
/* pixels */
"                ",
"                ",
"  .....  OX    X",
" .     o  OX  XO",
".       o  OXXO ",
"o ++    o   XO  ",
"o ++    o  XO   ",
"o       o XO    ",
"@       o       ",
" @     o#       ",
"  @@@@o$##      ",
"        $##     ",
"         $##    ",
"          $     ",
"                ",
"                "};

/* XPM */
static char * mouse_phase_p0_xpm[] = {
"16 16 3 1",
"      c None",
".     c Black",
"a     c Blue",
"                ",
"                ",
"  .....         ",
"  ..   ..       ",
"  ..   ..       ",
"  ..   ..       ",
"  ..   ..       ",
"  ..   ..       ",
"  .....         ",
"  ..     aa     ",
"  ..    aaaa    ",
"  ..   aa  aa   ",
"  ..   aa  aa   ",
"  ..    aaaa    ",
"         aa     ",
"                "};
/* XPM */
static char * mouse_phase_p1_xpm[] = {
"16 16 3 1",
" 	c None",
".	c Black",
"a	c Red",
"                ",
"                ",
"  .....         ",
"  ..   ..       ",
"  ..   ..       ",
"  ..   ..       ",
"  ..   ..       ",
"  ..   ..       ",
"  .....         ",
"  ..      aa    ",
"  ..    aaaa    ",
"  ..    aaaa    ",
"  ..      aa    ",
"  ..      aa    ",
"          aa    ",
"                "};
/* XPM */
static char * mouse_phase_i0_xpm[] = {
"16 16 3 1",
" 	c None",
".	c Black",
"a	c Blue",
"                ",
"                ",
" ......         ",
" ......         ",
"   ..           ",
"   ..           ",
"   ..           ",
"   ..           ",
"   ..           ",
"   ..      aa   ",
"   ..     aaaa  ",
"   ..    aa  aa ",
" ......  aa  aa ",
" ......   aaaa  ",
"           aa   ",
"                "};


/* XPM */
static char * mouse_select_xpm[] = {
"16 16 2 1",
"# c #000000",
". c None",
"................",
".....#..........",
".....##.........",
".....###........",
".....####.......",
".....#####......",
".....######.....",
".....#######....",
".....########...",
".....#####......",
".....##.##......",
".....#...##.....",
".........##.....",
"..........##....",
"..........##....",
"................"};


/* XPM */
static char * mouse_calibrate_xpm[] = {
"16 16 4 1",
" 	c None",
".	c black",
"X	c white",
"o	c black",
" oooo           ",
" o   o          ",
" o   o          ",
" oooo           ",
" o              ",
" o   oooo       ",
" o   o   o      ",
"     o   o      ",
"     oooo       ",
"     o          ",
"     o   o    o ",
"     o   oo  oo ",
"         o oo o ",
"         o oo o ",
"         o    o ",
"         o    o "};

/* XPM */
static char * mouse_integrate_xpm[] = {
"16 16 4 1",
" 	c None",
"o	c black",
"X	c white",
".	c blue",
"   ..           ",
"  .  .          ",
"    .    oo     ",
"  ....  o  o    ",
"       o        ",
"       o        ",
"       o        ",
"       o        ",
"       o        ",
"       o        ",
"       o        ",
"       o        ",
"   o  o   .     ",
"    oo   ..     ",
"          .     ",
"         ...    "};

/* XPM */
static char * mouse_peakpick_xpm[] = {
"16 16 7 1",
" 	c None",
".	c blue",
"X	c white",
"o	c #787c78",
"O	c #383838",
"+	c #b8b8b8",
"@	c #582020",
"                ",
"            o   ",
"       o   Ooo  ",
"  .    O+ OOO   ",
" ..    O+OOO    ",
"  .    OOOO     ",
"  .    OOO++    ",
"       OOOOOo   ",
"     O          ",
"     O          ",
"     O          ",
"     O          ",
"     O          ",
"    O @         ",
"OOOOO OOOOOOOOO ",
"                "};

/* XPM */
static char * mouse_distance_xpm[] = {
"16 16 3 1",
" 	c None",
".	c black",
"X	c white",
"                ",
"   .        .   ",
"  .          .  ",
" .............. ",
"  .          .  ",
"   .        .   ",
"        ..      ",
"        ..      ",
"        ..      ",
"    ......      ",
"   ..   ..      ",
"   ..   ..      ",
"   ..   ..      ",
"    ......      ",
"                ",
"                "};

/* XPM */
static char * mouse_rowcol_xpm[] = {
"16 16 4 1",
" 	c None",
"o	c black",
"X	c white",
".	c #383838",
"                ",
"                ",
"     o          ",
"    ooo         ",
"   ooooo        ",
"     o          ",
"     o          ",
"     o          ",
"     o      o   ",
"     o      oo  ",
" oooooooooooooo ",
"     o      oo  ",
"     o      o   ",
"     o          ",
"     o          ",
"                "};

/* XPM */
static char * mouse_rowcol_plane_xpm[] = {
"16 16 5 1",
" 	c Red",
"o	c black",
"X	c white",
".	c blue",
"a	c #ffffff",
"aaaaaaaa        ",
"aaaaaaaa        ",
"aaaoaaaa        ",
"aaoooaaa        ",
"aoooooaa        ",
"aaaoaaaa        ",
"aaaoaaaa........",
"aaaoaaa.........",
"aaaoaa..........",
"aaaoa...........",
"aaao......X.....",
"aaa.......XX....",
"aa..XXXXXXXXXX..",
"a.........XX....",
"..........X.....",
"................"};

/* XPM */
static char * mouse_sum_xpm[] = {
"16 16 7 1",
" 	c None",
".	c black",
"X	c #8080ff",
"o	c #aaaaff",
"O	c #bbbbff",
"+	c #0000ff",
"@	c #ccccff",
"                ",
".........       ",
" ........       ",
" ..      .      ",
"  ..            ",
"   ..           ",
"    ..          ",
"   .            ",
"  .      .    O ",
" ........  +  O ",
".........  +  O ",
"    O      +  O ",
" OOOOOOOOOO+OOOO",
"       +   +    ",
"++++++++++++++++",
"                "};

/* XPM */
static char * mouse_scale_xpm[] = {
"16 16 3 1",
" 	c None",
".	c None",
"X	c black",
"                ",
"                ",
"     X    X     ",
"    XXX   X     ",
"   XXXXX  X     ",
"     X    X     ",
"     X    X     ",
"     X    X     ",
"     X    X     ",
"     X    X     ",
"     X  XXXXX   ",
"     X   XXX    ",
"     X    X     ",
"                ",
"                ",
"                "};

/* XPM */
static char * mouse_noise_xpm[] = {
"16 16 4 1",
" 	c None",
".	c blue",
"X	c red",
"a	c black",
"  X.        .  a",
"a    .  a .     ",
"  .             ",
"   a    a   X   ",
"    .  X      . ",
" a   X          ",
"  .     .  .  X ",
"      a         ",
"        .   a   ",
"  .  X       a  ",
"     .     X    ",
"  X      .   .  ",
"    a .   X   a ",
"  X     .   .   ",
"     .          ",
"  .a   X   . a  "};

/* XPM */
static char * mouse_region_xpm[] = {
"16 16 3 1",
" 	c None",
".	c None",
"X	c black",
"                ",
"                ",
"  XXXXX   XXXX  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"  X   X   X  X  ",
"XXX   XXXXX  XXX",
"                ",
"                ",
"                "};
/* XPM */
static char * mouse_spline_xpm[] = {
"16 16 3 1",
" 	c None",
".	c None",
"x	c black",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"    xxx         ",
"   x   x      xx",
"  x     x    x  ",
"xx       x  x   ",
"          xx    ",
"                ",
"                "};
/* XPM */
static char * mouse_linefit_xpm[] = {
"16 16 3 1",
" 	c None",
".	c Red",
"x	c Blue",
"                ",
"                ",
"            .   ",
"        .  . .  ",
"        .. . .  ",
"  x     . .  .  ",
" x x    .    .  ",
" x x    .     . ",
" x  x  .      . ",
" x  x .       . ",
" x   x        . ",
" x   x         .",
" x  . x        .",
"x  .   xxx     .",
"                ",
"                "};

/* XPM */
static char * mouse_baseline_xpm[] = {
"16 16 3 1",
" 	c None",
".	c Red",
"x	c Blue",
"       .        ",
"       .        ",
"       .        ",
"       .        ",
"        .       ",
"         .      ",
"          .     ",
"           .....",
"...             ",
"   .            ",
"    .           ",
"     .          ",
"     .          ",
"     .          ",
"     .          ",
"     .          "};

/* XPM */
static char * mouse_waterfit_xpm[] = {
"16 16 3 1",
" 	c None",
".	c Red",
"x	c Blue",
"      .  .      ",
"      .  .      ",
"      .  .      ",
"      .  .      ",
"      .  .      ",
"      .  .      ",
"     .    .     ",
"     .    .     ",
"     .    .     ",
"     .    .     ",
"     .    .     ",
"    .      .    ",
"    .      .    ",
"....        ....",
"                ",
"                "};

/* XPM */
static char * mouse_watwa_xpm[] = {
"16 16 3 1",
" 	c None",
".	c Red",
"x	c Blue",
"      .  .      ",
"      .  .      ",
"      .  .      ",
"x     .  .      ",
"xx    .  .      ",
"xxx   .  .      ",
"xxxxx.x   .     ",
"xxxxx.xxxx.xxxxx",
"xxxxx.x   .     ",
"xx   .    .     ",
"x    .    .     ",
"    .      .    ",
"    .      .    ",
"....        ....",
"                ",
"                "};

/* XPM */
static char * mouse_transition_xpm[] = {
"16 16 3 1",
" 	c None",
".	c None",
"x	c black",
"                ",
"             x  ",
"          x  x  ",
"          x  x  ",
"          x  x  ",
"          x  x  ",
"     x    x  x  ",
"  x  x    x  x  ",
"  x  x    x  x  ",
"  x  x    x  x  ",
"  x  x    x  x  ",
"  x  x    x  x  ",
"xxxxxxxxxxxxxxxx",
"                ",
"                ",
"                "};
