/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 17-Jun-2008 11:58:20 by Hibernate Tools 3.2.0.b9



/**
* DisRefine generated by hbm2java
*/
public class DisRefine  implements java.io.Serializable {


     private int disRefId;
     private Integer profileId;
     private Integer digestId;
     private Integer glycanId;
     private String enzyme;
     private String product;
     private Integer productId;

    public DisRefine() {
    }

    
    public DisRefine(int disRefId) {
        this.disRefId = disRefId;
    }
    public DisRefine(int disRefId, Integer profileId, Integer digestId, Integer glycanId, String enzyme, String product, Integer productId) {
       this.disRefId = disRefId;
       this.profileId = profileId;
       this.digestId = digestId;
       this.glycanId = glycanId;
       this.enzyme = enzyme;
       this.product = product;
       this.productId = productId;
    }
   
    public int getDisRefId() {
        return this.disRefId;
    }
    
    public void setDisRefId(int disRefId) {
        this.disRefId = disRefId;
    }
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    public Integer getDigestId() {
        return this.digestId;
    }
    
    public void setDigestId(Integer digestId) {
        this.digestId = digestId;
    }
    public Integer getGlycanId() {
        return this.glycanId;
    }
    
    public void setGlycanId(Integer glycanId) {
        this.glycanId = glycanId;
    }
    public String getEnzyme() {
        return this.enzyme;
    }
    
    public void setEnzyme(String enzyme) {
        this.enzyme = enzyme;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }




}


