/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 21-Jan-2008 14:42:44 by Hibernate Tools 3.2.0.b9

//  stdlib imports
import java.util.HashSet;
import java.util.Set;

import java.io.Serializable;

//  eurocarb imports
import org.eurocarbdb.dataaccess.BasicEurocarbObject;
import static org.eurocarbdb.dataaccess.Eurocarb.getEntityManager;



import org.eurocarbdb.dataaccess.BasicEurocarbObject;


/**
* Glycan generated by hbm2java
*/
public class Glycan extends BasicEurocarbObject implements java.io.Serializable {


     private int glycanId;
     private String name;
     private double gu;
     private String ms;
     private String msMs;
     private Short hex;
     private Short hexnac;
     private Short neunac;
     private Short fucose;
     private Short xylose;
     private Short neugc;
     private Short a1;
     private Short a2;
     private Short a3;
     private Short a4;
     private Short s;
     private Short f6;
     private Short b;
     private Short bgal;
     private Short agal;
     private Short galnac;
     private Short polylac;
     private Short fouterarm;
     private Short hybrid;
     private Short mannose;
     private Short allGroups;
     private Short plant;
     private Short serum;
     private Short normalIgg;
     private Double std;
     private Integer ogbitranslation;

     private Set<GlycanSourceLink> glycanSourceLinks = new HashSet<GlycanSourceLink>(0);
     private Set<HplcPeaksAnnotated> hplcPeaksAnnotateds = new HashSet<HplcPeaksAnnotated>(0);

    public Glycan() {
    }

    
    public Glycan(int glycanId, String name, double gu) {
        this.glycanId = glycanId;
        this.name = name;
        this.gu = gu;
    }
    public Glycan(int glycanId, String name, double gu, String ms, String msMs, Short hex, Short hexnac, Short neunac, Short fucose, Short xylose, Short neugc, Short a1, Short a2, Short a3, Short a4, Short s, Short f6, Short b, Short bgal, Short agal, Short galnac, Short polylac, Short fouterarm, Short hybrid, Short mannose, Short allGroups, Short plant, Short serum, Short normalIgg, Double std, Integer ogbitranslation) {
       this.glycanId = glycanId;
       this.name = name;
       this.gu = gu;
       this.ms = ms;
       this.msMs = msMs;
       this.hex = hex;
       this.hexnac = hexnac;
       this.neunac = neunac;
       this.fucose = fucose;
       this.xylose = xylose;
       this.neugc = neugc;
       this.a1 = a1;
       this.a2 = a2;
       this.a3 = a3;
       this.a4 = a4;
       this.s = s;
       this.f6 = f6;
       this.b = b;
       this.bgal = bgal;
       this.agal = agal;
       this.galnac = galnac;
       this.polylac = polylac;
       this.fouterarm = fouterarm;
       this.hybrid = hybrid;
       this.mannose = mannose;
       this.allGroups = allGroups;
       this.plant = plant;
       this.serum = serum;
       this.normalIgg = normalIgg;
       this.std = std;
       this.ogbitranslation = ogbitranslation;
    }
   
    public int getGlycanId() {
        return this.glycanId;
    }
    
    public void setGlycanId(int glycanId) {
        this.glycanId = glycanId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getGu() {
        return this.gu;
    }
    
    public void setGu(double gu) {
        this.gu = gu;
    }
    public String getMs() {
        return this.ms;
    }
    
    public void setMs(String ms) {
        this.ms = ms;
    }
    public String getMsMs() {
        return this.msMs;
    }
    
    public void setMsMs(String msMs) {
        this.msMs = msMs;
    }
    public Short getHex() {
        return this.hex;
    }
    
    public void setHex(Short hex) {
        this.hex = hex;
    }
    public Short getHexnac() {
        return this.hexnac;
    }
    
    public void setHexnac(Short hexnac) {
        this.hexnac = hexnac;
    }
    public Short getNeunac() {
        return this.neunac;
    }
    
    public void setNeunac(Short neunac) {
        this.neunac = neunac;
    }
    public Short getFucose() {
        return this.fucose;
    }
    
    public void setFucose(Short fucose) {
        this.fucose = fucose;
    }
    public Short getXylose() {
        return this.xylose;
    }
    
    public void setXylose(Short xylose) {
        this.xylose = xylose;
    }
    public Short getNeugc() {
        return this.neugc;
    }
    
    public void setNeugc(Short neugc) {
        this.neugc = neugc;
    }
    public Short getA1() {
        return this.a1;
    }
    
    public void setA1(Short a1) {
        this.a1 = a1;
    }
    public Short getA2() {
        return this.a2;
    }
    
    public void setA2(Short a2) {
        this.a2 = a2;
    }
    public Short getA3() {
        return this.a3;
    }
    
    public void setA3(Short a3) {
        this.a3 = a3;
    }
    public Short getA4() {
        return this.a4;
    }
    
    public void setA4(Short a4) {
        this.a4 = a4;
    }
    public Short getS() {
        return this.s;
    }
    
    public void setS(Short s) {
        this.s = s;
    }
    public Short getF6() {
        return this.f6;
    }
    
    public void setF6(Short f6) {
        this.f6 = f6;
    }
    public Short getB() {
        return this.b;
    }
    
    public void setB(Short b) {
        this.b = b;
    }
    public Short getBgal() {
        return this.bgal;
    }
    
    public void setBgal(Short bgal) {
        this.bgal = bgal;
    }
    public Short getAgal() {
        return this.agal;
    }
    
    public void setAgal(Short agal) {
        this.agal = agal;
    }
    public Short getGalnac() {
        return this.galnac;
    }
    
    public void setGalnac(Short galnac) {
        this.galnac = galnac;
    }
    public Short getPolylac() {
        return this.polylac;
    }
    
    public void setPolylac(Short polylac) {
        this.polylac = polylac;
    }
    public Short getFouterarm() {
        return this.fouterarm;
    }
    
    public void setFouterarm(Short fouterarm) {
        this.fouterarm = fouterarm;
    }
    public Short getHybrid() {
        return this.hybrid;
    }
    
    public void setHybrid(Short hybrid) {
        this.hybrid = hybrid;
    }
    public Short getMannose() {
        return this.mannose;
    }
    
    public void setMannose(Short mannose) {
        this.mannose = mannose;
    }
    public Short getAllGroups() {
        return this.allGroups;
    }
    
    public void setAllGroups(Short allGroups) {
        this.allGroups = allGroups;
    }
    public Short getPlant() {
        return this.plant;
    }
    
    public void setPlant(Short plant) {
        this.plant = plant;
    }
    public Short getSerum() {
        return this.serum;
    }
    
    public void setSerum(Short serum) {
        this.serum = serum;
    }
    public Short getNormalIgg() {
        return this.normalIgg;
    }
    
    public void setNormalIgg(Short normalIgg) {
        this.normalIgg = normalIgg;
    }
    public Double getStd() {
        return this.std;
    }
    
    public void setStd(Double std) {
        this.std = std;
    }
    public Integer getOgbitranslation() {
        return this.ogbitranslation;
    }
    
    public void setOgbitranslation(Integer ogbitranslation) {
        this.ogbitranslation = ogbitranslation;
    }

    /*  getProfiles  *//******************************** 
    *
   */
    public Set<GlycanSourceLink> getGlycanSourceLinks()
    {
        return this.glycanSourceLinks;
    }


    /*  setProfiles  *//******************************** 
    *
    */
    public void setGlycanSourceLinks( Set<GlycanSourceLink> glycanSourceLinks )
    {
        this.glycanSourceLinks = glycanSourceLinks;
    }


    public Set<HplcPeaksAnnotated> getHplcPeaksAnnotateds()
    {
        return this.hplcPeaksAnnotateds;
    }


    /*  setProfiles  *//******************************** 
    *
    */
    public void setHplcPeaksAnnotateds( Set<HplcPeaksAnnotated> hplcPeaksAnnotateds )
    {
        this.hplcPeaksAnnotateds = hplcPeaksAnnotateds;
    }


    public static Glycan lookupById( int id )
    {
        //log.debug("looking up profile by profileId");
        Object i = getEntityManager()
                  .getQuery( "org.eurocarbdb.dataaccess.hplc.Glycan.BY_ID" )
                  .setParameter("glycanId", id )
                  .uniqueResult();

        assert i instanceof Glycan;

        return (Glycan) i;
    }

    public static Glycan lookupSequenceId ( int id)
    {
    Object i = getEntityManager()
           .getQuery( "org.eurocarbdb.dataaccess.hplc.Glycan.BY_SEQUENCE_ID")
           .setParameter("glycanId", id )
           .uniqueResult();

    assert i instanceof Glycan;

    return (Glycan) i;
    }

    public static Glycan lookupByGWS ( int id)
    {
    Object i = getEntityManager()
           .getQuery("org.eurocarbdb.dataaccess.hplc.Glycan.LOOKUP_BY_GWS")
           .setParameter("ogbitranslation", id)
           .uniqueResult();

    assert i instanceof Glycan;

    return (Glycan) i;
     }

     public static Glycan lookupAllById ( int id)
     {
    Object i = getEntityManager()
               .getQuery("org.eurocarbdb.dataaccess.hplc.Glycan.LOOKUP_BY_GLYCANID")
               .setParameter("glycanId", id)
               .uniqueResult();

    assert i instanceof Glycan;

    return (Glycan) i;
      }


}


