/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 16-May-2008 14:43:03 by Hibernate Tools 3.2.0.b9



/**
* GlycanTissue generated by hbm2java
*/
public class GlycanTissue  implements java.io.Serializable {


     private int glycanTissueId;
     private Integer glycanId;
     private String meshId;

    public GlycanTissue() {
    }

    
    public GlycanTissue(int glycanTissueId) {
        this.glycanTissueId = glycanTissueId;
    }
    public GlycanTissue(int glycanTissueId, Integer glycanId, String meshId) {
       this.glycanTissueId = glycanTissueId;
       this.glycanId = glycanId;
       this.meshId = meshId;
    }
   
    public int getGlycanTissueId() {
        return this.glycanTissueId;
    }
    
    public void setGlycanTissueId(int glycanTissueId) {
        this.glycanTissueId = glycanTissueId;
    }
    public Integer getGlycanId() {
        return this.glycanId;
    }
    
    public void setGlycanId(Integer glycanId) {
        this.glycanId = glycanId;
    }
    public String getMeshId() {
        return this.meshId;
    }
    
    public void setMeshId(String meshId) {
        this.meshId = meshId;
    }




}


