/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 28-Jan-2008 14:45:25 by Hibernate Tools 3.2.0.b9


import java.math.BigDecimal;
import java.util.Date;

/**
* GlycanSequenceTemp generated by hbm2java
*/
public class GlycanSequenceTemp  implements java.io.Serializable {


     private int glycanSequenceId;
     private String sequenceIupac;
     private String sequenceCt;
     private String sequenceCtCondensed;
     private Short residueCount;
     private BigDecimal massMonoisotopic;
     private BigDecimal massAverage;
     private String composition;
     private Date dateEntered;
     private Date dateContributed;
     private int contributorId;

    public GlycanSequenceTemp() {
    }

    
    public GlycanSequenceTemp(int glycanSequenceId, String sequenceIupac, String sequenceCt, String sequenceCtCondensed, Date dateEntered, Date dateContributed, int contributorId) {
        this.glycanSequenceId = glycanSequenceId;
        this.sequenceIupac = sequenceIupac;
        this.sequenceCt = sequenceCt;
        this.sequenceCtCondensed = sequenceCtCondensed;
        this.dateEntered = dateEntered;
        this.dateContributed = dateContributed;
        this.contributorId = contributorId;
    }
    public GlycanSequenceTemp(int glycanSequenceId, String sequenceIupac, String sequenceCt, String sequenceCtCondensed, Short residueCount, BigDecimal massMonoisotopic, BigDecimal massAverage, String composition, Date dateEntered, Date dateContributed, int contributorId) {
       this.glycanSequenceId = glycanSequenceId;
       this.sequenceIupac = sequenceIupac;
       this.sequenceCt = sequenceCt;
       this.sequenceCtCondensed = sequenceCtCondensed;
       this.residueCount = residueCount;
       this.massMonoisotopic = massMonoisotopic;
       this.massAverage = massAverage;
       this.composition = composition;
       this.dateEntered = dateEntered;
       this.dateContributed = dateContributed;
       this.contributorId = contributorId;
    }
   
    public int getGlycanSequenceId() {
        return this.glycanSequenceId;
    }
    
    public void setGlycanSequenceId(int glycanSequenceId) {
        this.glycanSequenceId = glycanSequenceId;
    }
    public String getSequenceIupac() {
        return this.sequenceIupac;
    }
    
    public void setSequenceIupac(String sequenceIupac) {
        this.sequenceIupac = sequenceIupac;
    }
    public String getSequenceCt() {
        return this.sequenceCt;
    }
    
    public void setSequenceCt(String sequenceCt) {
        this.sequenceCt = sequenceCt;
    }
    public String getSequenceCtCondensed() {
        return this.sequenceCtCondensed;
    }
    
    public void setSequenceCtCondensed(String sequenceCtCondensed) {
        this.sequenceCtCondensed = sequenceCtCondensed;
    }
    public Short getResidueCount() {
        return this.residueCount;
    }
    
    public void setResidueCount(Short residueCount) {
        this.residueCount = residueCount;
    }
    public BigDecimal getMassMonoisotopic() {
        return this.massMonoisotopic;
    }
    
    public void setMassMonoisotopic(BigDecimal massMonoisotopic) {
        this.massMonoisotopic = massMonoisotopic;
    }
    public BigDecimal getMassAverage() {
        return this.massAverage;
    }
    
    public void setMassAverage(BigDecimal massAverage) {
        this.massAverage = massAverage;
    }
    public String getComposition() {
        return this.composition;
    }
    
    public void setComposition(String composition) {
        this.composition = composition;
    }
    public Date getDateEntered() {
        return this.dateEntered;
    }
    
    public void setDateEntered(Date dateEntered) {
        this.dateEntered = dateEntered;
    }
    public Date getDateContributed() {
        return this.dateContributed;
    }
    
    public void setDateContributed(Date dateContributed) {
        this.dateContributed = dateContributed;
    }
    public int getContributorId() {
        return this.contributorId;
    }
    
    public void setContributorId(int contributorId) {
        this.contributorId = contributorId;
    }




}


