/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 12-Apr-2008 11:32:17 by Hibernate Tools 3.2.0.b9



/**
* GlycanSourceLink generated by hbm2java
*/
public class GlycanSourceLink  implements java.io.Serializable {


     private int sourceId;
     private int glycanId;
     private int refId;
     private int meshPertId;
     private int meshDiseaseId;
     private int meshTissueId;
     private int taxSpeciesId;
     private Integer biologicalContextId;

     private Glycan glycan;

    public GlycanSourceLink() {
    }

    
    public GlycanSourceLink(int sourceId, int glycanId, int refId, int meshPertId, int meshDiseaseId, int meshTissueId, int taxSpeciesId) {
        this.sourceId = sourceId;
        this.glycanId = glycanId;
        this.refId = refId;
        this.meshPertId = meshPertId;
        this.meshDiseaseId = meshDiseaseId;
        this.meshTissueId = meshTissueId;
        this.taxSpeciesId = taxSpeciesId;
    }
    public GlycanSourceLink(int sourceId, int glycanId, int refId, int meshPertId, int meshDiseaseId, int meshTissueId, int taxSpeciesId, Integer biologicalContextId) {
       this.sourceId = sourceId;
       this.glycanId = glycanId;
       this.refId = refId;
       this.meshPertId = meshPertId;
       this.meshDiseaseId = meshDiseaseId;
       this.meshTissueId = meshTissueId;
       this.taxSpeciesId = taxSpeciesId;
       this.biologicalContextId = biologicalContextId;
    }
   
    public int getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(int sourceId) {
        this.sourceId = sourceId;
    }
    public int getGlycanId() {
        return this.glycanId;
    }
    
    public void setGlycanId(int glycanId) {
        this.glycanId = glycanId;
    }
    public int getRefId() {
        return this.refId;
    }
    
    public void setRefId(int refId) {
        this.refId = refId;
    }
    public int getMeshPertId() {
        return this.meshPertId;
    }
    
    public void setMeshPertId(int meshPertId) {
        this.meshPertId = meshPertId;
    }
    public int getMeshDiseaseId() {
        return this.meshDiseaseId;
    }
    
    public void setMeshDiseaseId(int meshDiseaseId) {
        this.meshDiseaseId = meshDiseaseId;
    }
    public int getMeshTissueId() {
        return this.meshTissueId;
    }
    
    public void setMeshTissueId(int meshTissueId) {
        this.meshTissueId = meshTissueId;
    }
    public int getTaxSpeciesId() {
        return this.taxSpeciesId;
    }
    
    public void setTaxSpeciesId(int taxSpeciesId) {
        this.taxSpeciesId = taxSpeciesId;
    }
    public Integer getBiologicalContextId() {
        return this.biologicalContextId;
    }
    
    public void setBiologicalContextId(Integer biologicalContextId) {
        this.biologicalContextId = biologicalContextId;
    }


    public Glycan getGlycan()
    {
        return this.glycan;
    }


    public void setGlycan( Glycan glycan )
    {
        this.glycan = glycan;
    }

}


