/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 16-May-2008 14:43:03 by Hibernate Tools 3.2.0.b9



/**
* GlycanTaxonomy generated by hbm2java
*/
public class GlycanTaxonomy  implements java.io.Serializable {


     private int glycanTaxId;
     private Integer glycanId;
     private Integer ncbiId;

    public GlycanTaxonomy() {
    }

    
    public GlycanTaxonomy(int glycanTaxId) {
        this.glycanTaxId = glycanTaxId;
    }
    public GlycanTaxonomy(int glycanTaxId, Integer glycanId, Integer ncbiId) {
       this.glycanTaxId = glycanTaxId;
       this.glycanId = glycanId;
       this.ncbiId = ncbiId;
    }
   
    public int getGlycanTaxId() {
        return this.glycanTaxId;
    }
    
    public void setGlycanTaxId(int glycanTaxId) {
        this.glycanTaxId = glycanTaxId;
    }
    public Integer getGlycanId() {
        return this.glycanId;
    }
    
    public void setGlycanId(Integer glycanId) {
        this.glycanId = glycanId;
    }
    public Integer getNcbiId() {
        return this.ncbiId;
    }
    
    public void setNcbiId(Integer ncbiId) {
        this.ncbiId = ncbiId;
    }




}


