/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 26-Nov-2007 12:20:56 by Hibernate Tools 3.2.0.b9



/**
* RefTaxLink generated by hbm2java
*/
public class RefTaxLink  implements java.io.Serializable {


     private int refTaxId;
     private int ogbiLinkId;
     private int meshPertId;
     private int meshDiseaseId;
     private int meshTissueId;
     private Integer taxOrderId;
     private Integer taxSpeciesId;
     private String pertName;
     private String diseaseName;
     private String tissueName;

    public RefTaxLink() {
    }

    
    public RefTaxLink(int refTaxId, int ogbiLinkId) {
        this.refTaxId = refTaxId;
        this.ogbiLinkId = ogbiLinkId;
    }
    public RefTaxLink(int refTaxId, int ogbiLinkId, int meshPertId, int meshDiseaseId, int meshTissueId, Integer taxOrderId, Integer taxSpeciesId, String pertName, String diseaseName, String tissueName) {
       this.refTaxId = refTaxId;
       this.ogbiLinkId = ogbiLinkId;
       this.meshPertId = meshPertId;
       this.meshDiseaseId = meshDiseaseId;
       this.meshTissueId = meshTissueId;
       this.taxOrderId = taxOrderId;
       this.taxSpeciesId = taxSpeciesId;
       this.pertName = pertName;
       this.diseaseName = diseaseName;
       this.tissueName = tissueName;
    }
   
    public int getRefTaxId() {
        return this.refTaxId;
    }
    
    public void setRefTaxId(int refTaxId) {
        this.refTaxId = refTaxId;
    }
    public int getOgbiLinkId() {
        return this.ogbiLinkId;
    }
    
    public void setOgbiLinkId(int ogbiLinkId) {
        this.ogbiLinkId = ogbiLinkId;
    }
    public int getMeshPertId() {
        return this.meshPertId;
    }
    
    public void setMeshPertId(int meshPertId) {
        this.meshPertId = meshPertId;
    }
    public int getMeshDiseaseId() {
        return this.meshDiseaseId;
    }
    
    public void setMeshDiseaseId(int meshDiseaseId) {
        this.meshDiseaseId = meshDiseaseId;
    }
    public int getMeshTissueId() {
        return this.meshTissueId;
    }
    
    public void setMeshTissueId(int meshTissueId) {
        this.meshTissueId = meshTissueId;
    }
    public Integer getTaxOrderId() {
        return this.taxOrderId;
    }
    
    public void setTaxOrderId(Integer taxOrderId) {
        this.taxOrderId = taxOrderId;
    }
    public Integer getTaxSpeciesId() {
        return this.taxSpeciesId;
    }
    
    public void setTaxSpeciesId(Integer taxSpeciesId) {
        this.taxSpeciesId = taxSpeciesId;
    }
    public String getPertName() {
        return this.pertName;
    }
    
    public void setPertName(String pertName) {
        this.pertName = pertName;
    }
    public String getDiseaseName() {
        return this.diseaseName;
    }
    
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }
    public String getTissueName() {
        return this.tissueName;
    }
    
    public void setTissueName(String tissueName) {
        this.tissueName = tissueName;
    }




}


