/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1210 $ by $Author: glycoslave $ on $Date:: 2009-06-12 #$  
*/
package org.eurocarbdb.dataaccess.hplc;
// Generated 22-Oct-2008 14:55:21 by Hibernate Tools 3.2.0.b9



/**
* StructuresGlycoct generated by hbm2java
*/
public class StructuresGlycoct  implements java.io.Serializable {


     private int structuresId;
     private Integer glycanId;
     private String seqCt;
     private Integer glycanSequenceId;

    public StructuresGlycoct() {
    }

    
    public StructuresGlycoct(int structuresId) {
        this.structuresId = structuresId;
    }
    public StructuresGlycoct(int structuresId, Integer glycanId, String seqCt, Integer glycanSequenceId) {
       this.structuresId = structuresId;
       this.glycanId = glycanId;
       this.seqCt = seqCt;
       this.glycanSequenceId = glycanSequenceId;
    }
   
    public int getStructuresId() {
        return this.structuresId;
    }
    
    public void setStructuresId(int structuresId) {
        this.structuresId = structuresId;
    }
    public Integer getGlycanId() {
        return this.glycanId;
    }
    
    public void setGlycanId(Integer glycanId) {
        this.glycanId = glycanId;
    }
    public String getSeqCt() {
        return this.seqCt;
    }
    
    public void setSeqCt(String seqCt) {
        this.seqCt = seqCt;
    }
    public Integer getGlycanSequenceId() {
        return this.glycanSequenceId;
    }
    
    public void setGlycanSequenceId(Integer glycanSequenceId) {
        this.glycanSequenceId = glycanSequenceId;
    }




}


