/*
*   EuroCarbDB, a framework for carbohydrate bioinformatics
*
*   Copyright (c) 2006-2009, Eurocarb project, or third-party contributors as
*   indicated by the @author tags or express copyright attribution
*   statements applied by the authors.  
*
*   This copyrighted material is made available to anyone wishing to use, modify,
*   copy, or redistribute it subject to the terms and conditions of the GNU
*   Lesser General Public License, as published by the Free Software Foundation.
*   A copy of this license accompanies this distribution in the file LICENSE.txt.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
*   for more details.
*
*   Last commit: $Rev: 1147 $ by $Author: glycoslave $ on $Date:: 2009-06-04 #$  
*/

package org.eurocarbdb.util.carbbank;

/**
*   This is a package-private enumeration of human-extracted
*   and verified associations of Carbbank taxonomy to NCBI
*   taxonomy. The enum names themselves are totally arbitrary.
*   @author mjh
*/
enum CarbbankTaxonomy
{
    ab( "acacia", "Acacia", 3808 ),
    ac( "adenovirus 2", "unidentified adenovirus", 10535 ),
    ad( "Alaskan pollack", "Pollachius pollachius", 185739 ),
    ae( "Alaskan pollack cod fish", "Pollachius pollachius", 185739 ),
    af( "alfalfa", "Medicago sativa", 3879 ),
    ag( "algae", "!", -2 ),
    ah( "American ginseng", "Panax", 4053 ),
    ai( "aphid", "Eriosoma lanigerum", 133082 ),
    aj( "apple", "Malus x domestica", 3750 ),
    ak( "Aralia", "Aralia", 13340 ),
    al( "armadillo", "Armadillo", 96820 ),
    am( "aspen", "Populus tremula", 113636 ),
    an( "avacado", "Persea americana", 3435 ),
    ao( "avian influenza virus", "unidentified influenza virus", 11309 ),
    ap( "axenic mice", "Mus musculus", 10090 ),
    aq( "baboon", "Papio hamadryas", 9557 ),
    ar( "baculovirus", "unidentified baculovirus", 10469 ),
    as( "bael tree", "Aegle marmelos", 68527 ),
    at( "bamboo", "Bambusoideae", 147366 ),
    au( "banana", "Musa", -2 ),
    av( "barley", "Hordeum vulgare subsp. vulgare", 112509 ),
    aw( "basswood", "Tilia", 64580 ),
    ax( "bean", "Fabaceae", 3803 ),
    ay( "bee", "Apidae", 7458 ),
    az( "beetle", "Coleoptera", 7041 ),
    ba( "Bei-Wujiapi", "Asclepiadeae", 167488 ),
    bb( "beninabana", "Carthamus tinctorius", 4222 ),
    bc( "birch", "Betula", -2 ),
    bd( "bird", "Aves", 8782 ),
    be( "black medick trefoil", "Medicago lupulina", 47085 ),
    bf( "blackjack oak", "Quercus", 3511 ),
    bg( "blowfly", "Calliphoridae", 7371 ),
    bh( "bonnet monkey", "Macaca radiata", 9548 ),
    bi( "bottle-nose dolphin", "Tursiops truncatus", 9739 ),
    bj( "Bovine", "Bos taurus", 9913 ),
    bk( "brown algae", "Phaeophyceae", -2 ),
    bl( "bryophyte", "Bryophyta", 3208 ),
    bm( "buckthorn", "Rhamnus", 3609 ),
    bn( "Bunashimeij", "Hypsizygus marmoreus", 39966 ),
    bo( "butterfly weed", "Asclepias tuberosa", 141466 ),
    bp( "C57 Black mouse", "Mus sp.", 10095 ),
    bq( "cabbage", "Brassica oleracea var. capitata", 3716 ),
    br( "Canary bird bush", "Crotalaria", 3828 ),
    bs( "canine heartworm", "Dirofilaria immitis", 6287 ),
    bt( "carob", "Ceratonia siliqua", 20340 ),
    bu( "carrot", "Daucus carota", 4039 ),
    bv( "cascara", "Frangula purshiana", 55262 ),
    bw( "cashew", "Anacardium occidentale", 171929 ),
    bx( "cassava", "Manihot esculenta", 3983 ),
    by( "cast iron plant", "Aspidistra elatior", 39526 ),
    bz( "castor bean", "Ricinus communis", 3988 ),
    ca( "cat", "Felis catus", 9685 ),
    cb( "Cay Song Ran", "Albizia", 3812 ),
    cc( "cedar", "Cedrus", 3321 ),
    cd( "cedron", "Aloysia", 105887 ),
    ce( "chamomile", "Matricaria recutita", 127986 ),
    cf( "cheatgrass", "Bromus tectorum", 29667 ),
    cg( "chia", "Salvia", 21880 ),
    ch( "chicken", "Gallus gallus", 9031 ),
    ci( "chickpea", "Cicer arietinum", 3827 ),
    cj( "chinchilla", "Chinchillidae", -2 ),
    ck( "chinese hamster", "Cricetulus griseus", 10029 ),
    cl( "Chinese Paris", "!", -1 ),
    cm( "Chinese scholar tree", "Styphnolobium japonicum", 3897 ),
    cn( "Chinese swiftlet", "Collocalia", 46489 ),
    co( "Chrysanthemum", "Chrysanthemum", 13422 ),
    cp( "cichlid", "Cichlidae", 8113 ),
    cq( "Cineraria", "Cineraria", 82361 ),
    cr( "citrus", "Citrus", 2706 ),
    cs( "clam", "Bivalvia", 6544 ),
    ct( "clam worm", "Nereis", 6351 ),
    cu( "clover", "Trifolium", 3898 ),
    cv( "Coastal Bermuda grass", "Cynodon dactylon", 28909 ),
    cw( "cobra", "Naja", 8638 ),
    cx( "cockroach", "Blattaria", 85823 ),
    cy( "Coconut", "Cocos nucifera", 13894 ),
    cz( "cod fish", "Gadus", 8048 ),
    da( "comfrey", "Symphytum officinale", 278672 ),
    db( "common Atlantic starfish", "Asterias forbesii", 7603 ),
    dc( "common daisy", "Leucanthemum vulgare", 99072 ),
    dd( "coral", "Anthozoa", 6101 ),
    de( "coral tree", "Erythrina corallodendron", 3843 ),
    df( "corn", "Zea mays", 4577 ),
    dg( "coryneform", "Corynebacteriaceae", 1653 ),
    dh( "cotton", "Gossypium hirsutum", 3635 ),
    di( "Cowpea", "Vigna unguiculata", -2 ),
    dj( "cowpea rust fungus", "!", -1 ),
    dk( "crab", "Pleocyemata", 6692 ),
    dl( "cucumber", "Cucumis sativus", 3659 ),
    dm( "cucurbit", "Cucurbita", 3660 ),
    dn( "cycad", "Cycadales", 3297 ),
   _do( "dog", "Canis familiaris", 9615 ),
    dp( "dogfish", "Squalidae", 30511 ),
    dq( "dolphin", "Delphinus", 9727 ),
    dr( "Douglas fir", "Pseudotsuga menziesii", 3357 ),
    ds( "duck", "Anas platyrhynchos", 8839 ),
    dt( "earthworm", "Pheretima sieboldi", 6402 ),
    du( "eggplant", "Solanum melongena", 4111 ),
    dv( "Elder", "Sambucus nigra", 4202 ),
    dw( "electric ray", "Discopyge ommata", 7785 ),
    dx( "elm", "Ulmus", 24735 ),
    dy( "English daisy", "Bellis perennis", 41492 ),
    dz( "enteric bacteria", "!", -1 ),
    ea( "equine", "Equus", 9789 ),
    eb( "Fennel", "Foeniculum vulgare", 48038 ),
    ec( "fern", "Filicophyta", 3263 ),
    ed( "fig", "Ficus", 3493 ),
    ee( "finback whale", "Balaenoptera physalus", 9770 ),
    ef( "fish", "!", -1 ),
    eg( "flax", "Linum usitatissimum", 4006 ),
    eh( "flounder", "Pleuronectoidei", 30942 ),
    ei( "forb", "!", -1 ),
    ej( "fowl plague virus", "Fowl plague virus", 11313 ),
    ek( "fowl plague virus influenza virus", "unidentified influenza virus", 11309 ),
    el( "fox tapeworm", "Echinococcus multilocularis", 6211 ),
    em( "foxglove", "Digitalis", 4163 ),
    en( "fresh water bivalve", "Bivalvia", 6544 ),
    eo( "Friend murine leukemia virus", "Friend murine leukemia virus", 11795 ),
    ep( "Friend spleen focus-forming virus F-SFFV", "Friend mink cell focus-forming virus", 11783 ),
    eq( "Friend virus", "Friend murine leukemia virus", 11795 ),
    er( "frog", "Rana", 8399 ),
    es( "fruit fly", "Drosophila melanogaster", 7227 ),
    et( "garlic", "Allium sativum", 4682 ),
    eu( "gerbil", "Meriones", 10046 ),
    ev( "ginseng", "Panax ginseng", 4054 ),
    ew( "goat", "Capra hircus", 9925 ),
    ex( "golden spiny mouse", "Acomys russatus", 60746 ),
    ey( "goldfish", "Carassius auratus", 7957 ),
    ez( "gooseberry", "Ribes", 3801 ),
    fa( "gourd", "Cucurbitaceae", 3650 ),
    fb( "grass", "Poaceae", 4479 ),
    fc( "Green African monkey", "Cercopithecus sabaeus", 60711 ),
    fd( "green monkey", "Cercopithecus aethiops", 9534 ),
    fe( "green-bottle fly", "Lucilia sericata", 13632 ),
    ff( "guinea pig", "Cavia porcellus", 10141 ),
    fg( "Halobacteria", "Halobacteria", 183963 ),
    fh( "hamster", "Cricetinae", 10026 ),
    fi( "hardwood", "!", -1 ),
    fj( "haricot bean", "Phaseolus vulgaris", 3885 ),
    fk( "hedgehyssop", "Gratiola officinalis", 204382 ),
    fl( "hepatitis virus glycoprotein E1", "Hepatitis C virus", 11103 ),
    fm( "herpes simplex virus", "Herpes simplex virus unknown type", 126283 ),
    fn( "herring", "Clupeidae", 55118 ),
    fo( "HiB", "Haemophilus influenzae", 727 ),
    fp( "HIV", "Human immunodeficiency virus", -2 ),
    fq( "HIV-2", "Human immunodeficiency virus 2", 11709 ),
    fr( "hog", "Suidae", 9821 ),
    fs( "holly", "Ilex aquifolium", 4298 ),
    ft( "hollyhock", "Alcea rosea", 65557 ),
    fu( "honey locust", "Gleditsia triacanthos", 54874 ),
    fv( "honeydew from ergot", "Claviceps", 5110 ),
    fw( "honeysuckle", "Lonicera", 49606 ),
    fx( "hop", "Humulus", 3484 ),
    fy( "hornbeam", "Fagaceae", 3503 ),
    fz( "horse", "Equus caballus", 9796 ),
    ga( "horse chestnut", "Aesculus", 43363 ),
    gb( "horseradish", "Armoracia rusticana", 3704 ),
    gc( "horseshoe crab", "Limulidae", 6846 ),
    gd( "house musk shrew", "Soricidae", 9376 ),
    ge( "human", "Homo sapiens", 9606 ),
    gf( "human blood fluke", "Homo sapiens", 9606 ),
    gg( "human cytomegalovirus HCMV", "Human herpesvirus 5", 10359 ),
    gh( "human mouse", "!", -1 ),
    gi( "hyacinth bean", "Lablab purpureus", 35936 ),
    gj( "icefish", "!", -1 ),
    gk( "Iceland moss", "!", -1 ),
    gl( "influenza virus", "unidentified influenza virus", 11309 ),
    gm( "influenza virus A", "Influenza A virus", 11320 ),
    gn( "insect", "Insecta", 50557 ),
    go( "ivy", "Hedera helix", 4052 ),
    gp( "Japanese cedar", "Cryptomeria japonica", 3369 ),
    gq( "Japanese common char", "Salvelinus leucomaenis japonicus", 287195 ),
    gr( "Japanese monkey", "Macaca fuscata", 9542 ),
    gs( "Japanese morning glory", "Ipomoea nil", 35883 ),
    gt( "Japanese quail", "Coturnix japonica", 93934 ),
    gu( "jasmine", "Jasminum officinale", 126433 ),
    gv( "jellyfish", "Jasminum officinale", 126433 ),
    gw( "Jerusalem Artichoke", "Helianthus tuberosus", 4233 ),
    gx( "jojoba", "Simmondsia chinensis", 3999 ),
    gy( "Kentucky coffee tree", "Gymnocladus dioica", 53883 ),
    gz( "keyhole limpet", "Megathura crenulata", 55429 ),
    ha( "Kherzi", "!", -1 ),
    hb( "kidney bean", "Phaseolus vulgaris", 3885 ),
    hc( "Killi fish", "Fundulidae", 28756 ),
    hd( "king crab", "Chaceon affinis", 107258 ),
    he( "kiwi fruit", "Actinidiaceae", 3623 ),
    hf( "konjac", "Amorphophallus konjac", 78372 ),
    hg( "krill", "Euphausiacea", 6816 ),
    hh( "Ku-Ding-Cha", "Ilex latifolia", 53205 ),
    hi( "leech", "Hirudiniformes", 6416 ),
    hj( "lentil", "Lens culinaris", 3864 ),
    hk( "lichen", "!", -1 ),
    hl( "Licorice", "Glycyrrhiza", 46347 ),
    hm( "Lily turf", "Liriope spicata", 100521 ),
    hn( "liverwort", "Marchantia polymorpha", 3197 ),
    ho( "loach", "Botia", 98400 ),
    hp( "loquat", "Eriobotrya japonica", 32224 ),
    hq( "maize", "Zea mays", 4577 ),
    hr( "Malayan pit viper", "Calloselasma rhodostoma", 8717 ),
    hs( "maple", "Acer", 4022 ),
    ht( "Marburg virus", "Marburgvirus", 186537 ),
    hu( "marine bacterium", "uncultured marine bacterium", 56765 ),
    hv( "Medaka", "Oryziinae", 8088 ),
    hw( "Mexican axolotl", "Ambystoma mexicanum", 8296 ),
    hx( "Mexican lime", "Citrus aurantiifolia", 159033 ),
    hy( "millipede", "Diplopoda", 7553 ),
    hz( "mimosa", "Mimosa", 21013 ),
    ia( "mini-pig", "Suidae", 9821 ),
    ib( "mistletoe", "Santalales", 41947 ),
    ic( "mollusc", "Mollusca", 6447 ),
    id( "Mongolian larch", "Larix", 3325 ),
    ie( "monkey", "Primates", -2 ),
   _if( "montbretia", "Crocosmia", 58947 ),
    ig( "morning glory", "Ipomoeeae", 267213 ),
    ih( "mosquito", "Culicidae", 7157 ),
    ii( "mountain ash", "Sorbus", 23222 ),
    ij( "mouse", "Mus musculus", 10090 ),
    ik( "mouse C57Bl", "Mus musculus", 10090 ),
    il( "mouse rat bovine", "!", -1 ),
    im( "mouse-ear chickweed", "Cerastium", 3579 ),
    in( "Mouso-chiku bamboo", "Phyllostachys edulis", 38705 ),
    io( "mu tong", "Akebia trifoliata", 155132 ),
    ip( "mullet", "Mugilidae", 8189 ),
    iq( "mung bean", "Vigna radiata var. radiata", 3916 ),
    ir( "mushroom", "Fungi", 4751 ),
    is( "muskmelon", "Cucumis melo", 3656 ),
    it( "Mycoplasma fermentans", "Mycoplasma fermentans", 2115 ),
    iu( "nematode", "Nematoda", -2 ),
    iv( "New Zealand black mouse", "Mus musculus", 10090 ),
    iw( "Newcastle virus", "Newcastle disease virus", 11176 ),
    ix( "nuo-mi-xang-cao", "!", -1 ),
    iy( "oat", "Avena sativa", -2 ),
    iz( "oat in the ratio of 2.6:1", "Avena sativa", 4498 ),
    ja( "Okra", "Abelmoschus", 183218 ),
    jb( "Oleander", "Nerium oleander", 63479 ),
    jc( "onion", "Allium cepa", 4679 ),
    jd( "orchard grass", "Dactylis glomerata", 4509 ),
    je( "orchid", "Orchidaceae", 4747 ),
    jf( "ornamental tobacco", "Nicotiana alata", 4087 ),
    jg( "owl monkey", "Aotus trivirgatus", 9505 ),
    jh( "ox", "Bos taurus", 9913 ),
    ji( "oyster", "Ostreidae", 6563 ),
    jj( "pacific mackerel", "Scomber japonicus", 13676 ),
    jk( "pea", "Pisum sativum", 3888 ),
    jl( "peach", "Prunus persica", 3760 ),
    jm( "peony", "Paeonia", 13625 ),
    jn( "pepper", "!", -1 ),
    jo( "perennial ryegrass", "Lolium perenne", 4522 ),
    jp( "pig", "Sus scrofa", 9823 ),
    jq( "pigeon", "Columba", 8931 ),
    jr( "pigeon pea", "Cajanus cajan", 3821 ),
    js( "pine", "Pinus", 3337 ),
    jt( "Pineapple", "Ananas comosus", 4615 ),
    ju( "Pit viper", "Crotalinae", 8710 ),
    jv( "platypus", "Ornithorhynchus anatinus", -2 ),
    jw( "Pokeberry", "Phytolacca", 3526 ),
    jx( "pommerans", "Citrus aurantium", 43166 ),
    jy( "poplar", "Populus", 3689 ),
    jz( "poppy", "Papaveraceae", 3465 ),
    ka( "porcine", "Suidae", 9821 ),
    kb( "potato", "Solanum tuberosum", 4113 ),
    kc( "primrose", "Primula vulgaris", 175104 ),
    kd( "quail", "Galliformes", 8976 ),
    ke( "rabbit", "Oryctolagus cuniculus", 9986 ),
    kf( "rabies virus", "Rabies virus", 11292 ),
    kg( "radish", "Raphanus sativus", 3726 ),
    kh( "rainbow trout", "Oncorhynchus mykiss", 8022 ),
    ki( "rapeseed", "Brassica napus", 3708 ),
    kj( "raspberry", "Rubus idaeus", 32247 ),
    kk( "rat", "Rattus", -2 ),
    kl( "red clover", "Trifolium pratense", 57577 ),
    km( "red currant", "Ribes rubrum", 175228 ),
    kn( "red marine algae", "Rhodophyta", 2763 ),
    ko( "red spruce", "Picea rubens", 3333 ),
    kp( "red squill", "Scilla", 4701 ),
    kq( "red wine", "!", -1 ),
    kr( "red-spotted newt", "Notophthalmus viridescens", 8316 ),
    ks( "rhesus monkey", "Macaca mulatta", 9544 ),
    kt( "rice", "Oryza sativa", -2 ),
    ku( "Rosemallow", "Hibiscus", 47605 ),
    kv( "rosemary", "Rosmarinus officinalis", 39367 ),
    kw( "rubber tree", "Hevea brasiliensis", 3981 ),
    kx( "rudd", "Scardinius erythrophthalmus", 58319 ),
    ky( "rye", "Secale cereale", 4550 ),
    kz( "ryegrass", "Lolium", 4520 ),
    la( "salamander", "Amphibia", 8292 ),
    lb( "salmon", "Salmonidae", 8015 ),
    lc( "scorpion", "Scorpiones", 6855 ),
    ld( "sea cucumber", "Holothuroidea", 7705 ),
    le( "sea hare", "!", -2 ),
    lf( "sea lion", "Otariidae", 9702 ),
    lg( "sea squirt", "Urochordata", 7712 ),
    lh( "sea urchin", "Echinoidea", 7625 ),
    li( "seaweed", "!", -1 ),
    lj( "Semliki Forest virus", "Semliki forest virus", 11033 ),
    lk( "Sendai virus", "Sendai virus", 11191 ),
    ll( "Senegae Radix", "Polygala senega", 174549 ),
    lm( "shark", "Elasmobranchii", 7778 ),
    ln( "sheep", "Ovis aries", 9940 ),
    lo( "shellfish", "!", -1 ),
    lp( "shrimp", "Caridea", 6694 ),
    lq( "Siberian hamster", "Phodopus sungorus", 10044 ),
    lr( "Silverleaf whitefly", "Bemisia argentifolii", 77855 ),
    ls( "Sinbis virus", "Sindbis virus", 11034 ),
    lt( "skate", "Rajidae", 30475 ),
    lu( "slippery-elm", "Ulmus rubra", 102693 ),
    lv( "snail", "Gastropoda", 6448 ),
    lw( "snake", "Serpentes", 8570 ),
    lx( "snowbell", "Soldanella", 59824 ),
    ly( "softwood", "!", -1 ),
    lz( "soybean", "Glycine max", 3847 ),
    ma( "spinach", "Spinacia oleracea", 3562 ),
    mb( "sponge", "Porifera", 6040 ),
    mc( "spruce", "Picea", 3328 ),
    md( "squash", "Cucurbita", 3660 ),
    me( "squid", "!", -1 ),
    mf( "starfish", "Asteroidea", 7588 ),
    mg( "strawberry", "Fragaria x ananassa", 3747 ),
    mh( "stumptail monkey", "Primates", 9443 ),
    mi( "sugar beet", "Beta vulgaris subsp. vulgaris", 3555 ),
    mj( "Sugarcane", "!", -2 ),
    mk( "sundew", "Drosera", 4363 ),
    ml( "sunflower", "Helianthus annuus", 4232 ),
    mm( "sunn hemp", "Crotalaria juncea", 3829 ),
    mn( "swallow", "Hirundinidae", 43148 ),
    mo( "swarm rat", "Rattus", 10114 ),
    mp( "sweet clover", "Melilotus officinalis", 47083 ),
    mq( "sycamore", "!", -1 ),
    mr( "sycamore maple", "Acer pseudoplatanus", 4026 ),
    ms( "Syrian golden hamster", "Mesocricetus auratus", 10036 ),
    mt( "tall fescue grass", "Festuca", 4605 ),
    mu( "tamarind", "Tamarindus indica", 58860 ),
    mv( "tammar wallaby", "Macropus eugenii", 9315 ),
    mw( "tapeworm", "Cestoda", 6199 ),
    mx( "taranoki", "Aralia elata", 82095 ),
    my( "tea", "Camellia sinensis", 4442 ),
    mz( "terrestrial slug", "Stylommatophora", 6527 ),
    na( "toad", "Bufonidae", 8382 ),
    nb( "tobacco", "Nicotiana tabacum", 4097 ),
    nc( "tobacco hornworm", "Manduca sexta", 7130 ),
    nd( "tomato", "Lycopersicon esculentum", 4081 ),
    ne( "Tora bean", "Phaseolus vulgaris", 3885 ),
    nf( "tribestan", "!", -1 ),
    ng( "trout", "Salmonidae", 8015 ),
    nh( "trypanosome", "Trypanosoma", 5690 ),
    ni( "turkey", "Meleagris gallopavo", 9103 ),
    nj( "turtle-dove", "Streptopelia turtur", 177155 ),
    nk( "vesicular stomatitis virus", "Vesicular stomatitis virus", 11276 ),
    nl( "virus", "Viruses", 10239 ),
    nm( "wallaby", "Macropodidae", 9307 ),
    nn( "water hyacinth", "Eichhornia crassipes", 44947 ),
    no( "water lily", "Nymphaeaceae", 4410 ),
    np( "western red cedar", "Cupressaceae", 3367 ),
    nq( "whale", "Cetacea", 9721 ),
    nr( "wheat", "Triticum aestivum", 4565 ),
    ns( "WHHL rabbit", "Oryctolagus cuniculus", 9986 ),
    nt( "white ginseng", "Araliaceae", 4050 ),
    nu( "white lupine", "Lupinus albus", 3870 ),
    nv( "wild garlic", "Allium ursinum", 4684 ),
    nw( "wild oat", "Bromus", 4501 ),
    nx( "willow", "Salix", 40685 ),
    ny( "woodrose", "Rosaceae", 3745 ),
    nz( "wool flower", "Celosia trigyna", 270123 ),
    oa( "Yabujirami", "Torilis japonica", 49576 ),
    ob( "yeast", "Saccharomyces cerevisiae", 4932 ),
    oc( "yellow sweetclover", "Melilotus officinalis", 47083 ),
    od( "Yu er", "!", -1 )
    ;
    
    
    public String carbbankName;
    public String ncbiName;
    public int    ncbiId;
    
    CarbbankTaxonomy( String cb_name, String ncbi_name, int ncbi_id )
    {
        carbbankName = cb_name;
        ncbiName = ncbi_name;
        ncbiId = ncbi_id;
    }
    
}
